var EMOJI_CATEGORIES = [
  {
    name: "Smileys & Emotion",
    items: [
      ["😀","grinning face","grinning"],
      ["😃","grinning face with big eyes","smiley"],
      ["😄","grinning face with smiling eyes","smile"],
      ["😁","beaming face with smiling eyes","grin"],
      ["😅","grinning face with sweat","sweat_smile"],
      ["🙂","slightly smiling face","slightly_smiling_face"],
      ["😉","winking face","wink"],
      ["😊","smiling face with smiling eyes","blush"],
      ["😇","smiling face with halo","innocent"],
      ["🤩","star-struck","star_struck"],
      ["😌","relieved face","relieved"],
      ["🥳","partying face","partying_face"],
      ["😎","smiling face with sunglasses","sunglasses"],
      ["🤓","nerd face","nerd_face"],
      ["🧐","face with monocle","monocle_face"],
      ["🤔","thinking face","thinking"],
      ["🫡","saluting face","saluting_face"],
      ["🤐","zipper-mouth face","zipper_mouth_face"],
      ["🤨","face with raised eyebrow","raised_eyebrow"],
      ["😐","neutral face","neutral_face"],
      ["😑","expressionless face","expressionless"],
      ["😶","face without mouth","no_mouth"],
      ["😏","smirking face","smirk"],
      ["😒","unamused face","unamused"],
      ["🙄","face with rolling eyes","roll_eyes"],
      ["😬","grimacing face","grimacing"],
      ["😮‍💨","face exhaling","face_exhaling"],
      ["😔","pensive face","pensive"],
      ["😴","sleeping face","sleeping"],
      ["😷","face with medical mask","mask"],
      ["🤒","face with thermometer","face_with_thermometer"],
      ["🤯","exploding head","exploding_head"],
      ["😕","confused face","confused"],
      ["😟","worried face","worried"],
      ["🙁","slightly frowning face","slightly_frowning_face"],
      ["😮","face with open mouth","open_mouth"],
      ["😲","astonished face","astonished"],
      ["😳","flushed face","flushed"],
      ["🥺","pleading face","pleading_face"],
      ["😨","fearful face","fearful"],
      ["😰","anxious face with sweat","cold_sweat"],
      ["😢","crying face","cry"],
      ["😭","loudly crying face","sob"],
      ["😱","face screaming in fear","scream"],
      ["😖","confounded face","confounded"],
      ["😞","disappointed face","disappointed"],
      ["😓","downcast face with sweat","sweat"],
      ["😩","weary face","weary"],
      ["😫","tired face","tired_face"],
      ["🥱","yawning face","yawning_face"],
      ["😤","face with steam from nose","triumph"],
      ["😡","enraged face","rage|pout"],
      ["😠","angry face","angry"],
      ["🤖","robot","robot"],
      ["❤️","red heart","heart"],
      ["💔","broken heart","broken_heart"],
      ["💯","hundred points","100"],
      ["💥","collision","boom|collision"],
      ["💦","sweat droplets","sweat_drops"],
      ["💨","dashing away","dash"],
      ["💬","speech balloon","speech_balloon"],
      ["👁️‍🗨️","eye in speech bubble","eye_speech_bubble"],
      ["🗨️","left speech bubble","left_speech_bubble"],
      ["🗯️","right anger bubble","right_anger_bubble"],
      ["💭","thought balloon","thought_balloon"],
      ["💤","ZZZ","zzz"]
    ],
  },
  {
    name: "People & Body",
    items: [
      ["👋","waving hand","wave"],
      ["🤚","raised back of hand","raised_back_of_hand"],
      ["🖐️","hand with fingers splayed","raised_hand_with_fingers_splayed"],
      ["✋","raised hand","hand|raised_hand"],
      ["👌","OK hand","ok_hand"],
      ["🤌","pinched fingers","pinched_fingers"],
      ["🤏","pinching hand","pinching_hand"],
      ["✌️","victory hand","v"],
      ["🤞","crossed fingers","crossed_fingers"],
      ["🤙","call me hand","call_me_hand"],
      ["👈","backhand index pointing left","point_left"],
      ["👉","backhand index pointing right","point_right"],
      ["👆","backhand index pointing up","point_up_2"],
      ["👇","backhand index pointing down","point_down"],
      ["☝️","index pointing up","point_up"],
      ["🫵","index pointing at the viewer","index_pointing_at_the_viewer"],
      ["👍","thumbs up","+1|thumbsup"],
      ["👎","thumbs down","-1|thumbsdown"],
      ["✊","raised fist","fist_raised|fist"],
      ["👊","oncoming fist","fist_oncoming|facepunch|punch"],
      ["👏","clapping hands","clap"],
      ["🙌","raising hands","raised_hands"],
      ["🫶","heart hands","heart_hands"],
      ["👐","open hands","open_hands"],
      ["🤲","palms up together","palms_up_together"],
      ["🤝","handshake","handshake"],
      ["🙏","folded hands","pray"],
      ["✍️","writing hand","writing_hand"],
      ["💪","flexed biceps","muscle"],
      ["🧠","brain","brain"],
      ["👀","eyes","eyes"],
      ["👁️","eye","eye"],
      ["🧑","person","adult"],
      ["👨","man","man"],
      ["👩","woman","woman"],
      ["🙋","person raising hand","raising_hand"],
      ["🙋‍♂️","man raising hand","raising_hand_man"],
      ["🙋‍♀️","woman raising hand","raising_hand_woman"],
      ["🙇","person bowing","bow"],
      ["🤦","person facepalming","facepalm"],
      ["🤦‍♂️","man facepalming","man_facepalming"],
      ["🤦‍♀️","woman facepalming","woman_facepalming"],
      ["🤷","person shrugging","shrug"],
      ["🤷‍♂️","man shrugging","man_shrugging"],
      ["🤷‍♀️","woman shrugging","woman_shrugging"],
      ["🧑‍⚕️","health worker","health_worker"],
      ["👨‍⚕️","man health worker","man_health_worker"],
      ["👩‍⚕️","woman health worker","woman_health_worker"],
      ["🧑‍🎓","student","student"],
      ["👨‍🎓","man student","man_student"],
      ["👩‍🎓","woman student","woman_student"],
      ["🧑‍🏫","teacher","teacher"],
      ["👨‍🏫","man teacher","man_teacher"],
      ["👩‍🏫","woman teacher","woman_teacher"],
      ["🧑‍⚖️","judge","judge"],
      ["👨‍⚖️","man judge","man_judge"],
      ["👩‍⚖️","woman judge","woman_judge"],
      ["🧑‍🍳","cook","cook"],
      ["🧑‍🔧","mechanic","mechanic"],
      ["🧑‍🏭","factory worker","factory_worker"],
      ["🧑‍💼","office worker","office_worker"],
      ["👨‍💼","man office worker","man_office_worker"],
      ["👩‍💼","woman office worker","woman_office_worker"],
      ["🧑‍🔬","scientist","scientist"],
      ["👨‍🔬","man scientist","man_scientist"],
      ["👩‍🔬","woman scientist","woman_scientist"],
      ["🧑‍💻","technologist","technologist"],
      ["👨‍💻","man technologist","man_technologist"],
      ["👩‍💻","woman technologist","woman_technologist"],
      ["🧑‍🎨","artist","artist"],
      ["🧑‍✈️","pilot","pilot"],
      ["🧑‍🚒","firefighter","firefighter"],
      ["👮","police officer","police_officer|cop"],
      ["🕵️","detective","detective"],
      ["💂","guard","guard"],
      ["👷","construction worker","construction_worker"],
      ["👷‍♂️","man construction worker","construction_worker_man"],
      ["👷‍♀️","woman construction worker","construction_worker_woman"],
      ["🚶","person walking","walking"],
      ["🏃","person running","runner|running"],
      ["🗣️","speaking head","speaking_head"],
      ["👤","bust in silhouette","bust_in_silhouette"],
      ["👥","busts in silhouette","busts_in_silhouette"],
      ["🫂","people hugging","people_hugging"]
    ],
  },
  {
    name: "Animals & Nature",
    items: [
      ["🐶","dog face","dog"],
      ["🐱","cat face","cat"],
      ["🦁","lion","lion"],
      ["🐴","horse face","horse"],
      ["🦊","fox","fox_face"],
      ["🐻","bear","bear"],
      ["🐼","panda","panda_face"],
      ["🦅","eagle","eagle"],
      ["🦉","owl","owl"],
      ["🕊️","dove","dove"],
      ["🐝","honeybee","bee|honeybee"],
      ["🐛","bug","bug"],
      ["🦠","microbe","microbe"],
      ["💐","bouquet","bouquet"],
      ["🌸","cherry blossom","cherry_blossom"],
      ["🌹","rose","rose"],
      ["🌻","sunflower","sunflower"],
      ["🌱","seedling","seedling"],
      ["🪴","potted plant","potted_plant"],
      ["🌲","evergreen tree","evergreen_tree"],
      ["🌳","deciduous tree","deciduous_tree"],
      ["🌴","palm tree","palm_tree"],
      ["🌵","cactus","cactus"],
      ["🌿","herb","herb"],
      ["☘️","shamrock","shamrock"],
      ["🍀","four leaf clover","four_leaf_clover"],
      ["🍁","maple leaf","maple_leaf"],
      ["🍂","fallen leaf","fallen_leaf"],
      ["🍃","leaf fluttering in wind","leaves"]
    ],
  },
  {
    name: "Food & Drink",
    items: [
      ["🍎","red apple","apple"],
      ["🍏","green apple","green_apple"],
      ["🍌","banana","banana"],
      ["🍊","tangerine","tangerine|orange|mandarin"],
      ["🍋","lemon","lemon"],
      ["🍇","grapes","grapes"],
      ["🍓","strawberry","strawberry"],
      ["🥑","avocado","avocado"],
      ["🍞","bread","bread"],
      ["🥨","pretzel","pretzel"],
      ["🧀","cheese wedge","cheese"],
      ["🍔","hamburger","hamburger"],
      ["🍕","pizza","pizza"],
      ["🥪","sandwich","sandwich"],
      ["🥗","green salad","green_salad"],
      ["🍿","popcorn","popcorn"],
      ["🍱","bento box","bento"],
      ["🍣","sushi","sushi"],
      ["🎂","birthday cake","birthday"],
      ["🍰","shortcake","cake"],
      ["🧁","cupcake","cupcake"],
      ["🍪","cookie","cookie"],
      ["🍩","doughnut","doughnut"],
      ["☕","hot beverage","coffee"],
      ["🫖","teapot","teapot"],
      ["🍵","teacup without handle","tea"],
      ["🥛","glass of milk","milk_glass"],
      ["🥤","cup with straw","cup_with_straw"],
      ["🧃","beverage box","beverage_box"],
      ["🍾","bottle with popping cork","champagne"],
      ["🍷","wine glass","wine_glass"],
      ["🍺","beer mug","beer"],
      ["🍻","clinking beer mugs","beers"],
      ["🥂","clinking glasses","clinking_glasses"],
      ["🧊","ice","ice_cube"],
      ["🍽️","fork and knife with plate","plate_with_cutlery"],
      ["🍴","fork and knife","fork_and_knife"]
    ],
  },
  {
    name: "Travel & Places",
    items: [
      ["🌍","globe showing Europe-Africa","earth_africa"],
      ["🌎","globe showing Americas","earth_americas"],
      ["🌏","globe showing Asia-Australia","earth_asia"],
      ["🌐","globe with meridians","globe_with_meridians"],
      ["🗺️","world map","world_map"],
      ["🧭","compass","compass"],
      ["🏔️","snow-capped mountain","mountain_snow"],
      ["⛰️","mountain","mountain"],
      ["🏖️","beach with umbrella","beach_umbrella"],
      ["🏟️","stadium","stadium"],
      ["🏛️","classical building","classical_building"],
      ["🏗️","building construction","building_construction"],
      ["🏠","house","house"],
      ["🏡","house with garden","house_with_garden"],
      ["🏢","office building","office"],
      ["🏣","Japanese post office","post_office"],
      ["🏤","post office","european_post_office"],
      ["🏥","hospital","hospital"],
      ["🏦","bank","bank"],
      ["🏨","hotel","hotel"],
      ["🏪","convenience store","convenience_store"],
      ["🏫","school","school"],
      ["🏬","department store","department_store"],
      ["🏭","factory","factory"],
      ["🏙️","cityscape","cityscape"],
      ["🌅","sunrise","sunrise"],
      ["🌇","sunset","city_sunrise"],
      ["🌉","bridge at night","bridge_at_night"],
      ["🚂","locomotive","steam_locomotive"],
      ["🚆","train","train2"],
      ["🚇","metro","metro"],
      ["🚌","bus","bus"],
      ["🚑","ambulance","ambulance"],
      ["🚒","fire engine","fire_engine"],
      ["🚓","police car","police_car"],
      ["🚕","taxi","taxi"],
      ["🚗","automobile","car|red_car"],
      ["🚙","sport utility vehicle","blue_car"],
      ["🚚","delivery truck","truck"],
      ["🚜","tractor","tractor"],
      ["🚲","bicycle","bike"],
      ["🚏","bus stop","busstop"],
      ["🛣️","motorway","motorway"],
      ["⛽","fuel pump","fuelpump"],
      ["🚨","police car light","rotating_light"],
      ["🚥","horizontal traffic light","traffic_light"],
      ["🚦","vertical traffic light","vertical_traffic_light"],
      ["🛑","stop sign","stop_sign"],
      ["🚧","construction","construction"],
      ["⚓","anchor","anchor"],
      ["⛵","sailboat","boat|sailboat"],
      ["🚢","ship","ship"],
      ["✈️️","airplane","airplane"],
      ["🛫","airplane departure","flight_departure"],
      ["🛬","airplane arrival","flight_arrival"],
      ["💺","seat","seat"],
      ["🚁","helicopter","helicopter"],
      ["🚀","rocket","rocket"],
      ["🧳","luggage","luggage"],
      ["⌛","hourglass done","hourglass"],
      ["⏳","hourglass not done","hourglass_flowing_sand"],
      ["⌚","watch","watch"],
      ["⏰","alarm clock","alarm_clock"],
      ["⏱️","stopwatch","stopwatch"],
      ["⏲️","timer clock","timer_clock"],
      ["🕰️","mantelpiece clock","mantelpiece_clock"],
      ["☀️","sun","sunny"],
      ["⭐","star","star"],
      ["🌟","glowing star","star2"],
      ["🌠","shooting star","stars"],
      ["☁️","cloud","cloud"],
      ["⛅","sun behind cloud","partly_sunny"],
      ["⛈️","cloud with lightning and rain","cloud_with_lightning_and_rain"],
      ["🌧️","cloud with rain","cloud_with_rain"],
      ["🌩️","cloud with lightning","cloud_with_lightning"],
      ["⚡","high voltage","zap"],
      ["❄️","snowflake","snowflake"],
      ["🔥","fire","fire"],
      ["💧","droplet","droplet"],
      ["🌊","water wave","ocean"]
    ],
  },
  {
    name: "Activities",
    items: [
      ["✨","sparkles","sparkles"],
      ["🎈","balloon","balloon"],
      ["🎉","party popper","tada"],
      ["🎊","confetti ball","confetti_ball"],
      ["🎀","ribbon","ribbon"],
      ["🎁","wrapped gift","gift"],
      ["🎟️","admission tickets","tickets"],
      ["🎫","ticket","ticket"],
      ["🎖️","military medal","medal_military"],
      ["🏆","trophy","trophy"],
      ["🏅","sports medal","medal_sports"],
      ["🥇","1st place medal","1st_place_medal"],
      ["🥈","2nd place medal","2nd_place_medal"],
      ["🥉","3rd place medal","3rd_place_medal"],
      ["⚽","soccer ball","soccer"],
      ["🏀","basketball","basketball"],
      ["🏈","american football","football"],
      ["🎾","tennis","tennis"],
      ["🎯","bullseye","dart"],
      ["🪄","magic wand","magic_wand"],
      ["🎮","video game","video_game"],
      ["🎲","game die","game_die"],
      ["🧩","puzzle piece","jigsaw"],
      ["🎭","performing arts","performing_arts"],
      ["🎨","artist palette","art"]
    ],
  },
  {
    name: "Objects",
    items: [
      ["👓","glasses","eyeglasses"],
      ["🕶️","sunglasses","dark_sunglasses"],
      ["🥽","goggles","goggles"],
      ["🥼","lab coat","lab_coat"],
      ["🦺","safety vest","safety_vest"],
      ["👔","necktie","necktie"],
      ["👕","t-shirt","shirt|tshirt"],
      ["🎒","backpack","school_satchel"],
      ["👑","crown","crown"],
      ["🎓","graduation cap","mortar_board"],
      ["🧢","billed cap","billed_cap"],
      ["⛑️","rescue worker’s helmet","rescue_worker_helmet"],
      ["💎","gem stone","gem"],
      ["🔇","muted speaker","mute"],
      ["🔈","speaker low volume","speaker"],
      ["🔉","speaker medium volume","sound"],
      ["🔊","speaker high volume","loud_sound"],
      ["📢","loudspeaker","loudspeaker"],
      ["📣","megaphone","mega"],
      ["🔔","bell","bell"],
      ["🔕","bell with slash","no_bell"],
      ["🎼","musical score","musical_score"],
      ["🎵","musical note","musical_note"],
      ["🎶","musical notes","notes"],
      ["🎙️","studio microphone","studio_microphone"],
      ["🎚️","level slider","level_slider"],
      ["🎛️","control knobs","control_knobs"],
      ["🎤","microphone","microphone"],
      ["🎧","headphone","headphones"],
      ["📻","radio","radio"],
      ["📱","mobile phone","iphone"],
      ["📲","mobile phone with arrow","calling"],
      ["☎️","telephone","phone|telephone"],
      ["📞","telephone receiver","telephone_receiver"],
      ["📠","fax machine","fax"],
      ["🔋","battery","battery"],
      ["🪫","low battery","low_battery"],
      ["🔌","electric plug","electric_plug"],
      ["💻","laptop","computer"],
      ["🖥️","desktop computer","desktop_computer"],
      ["🖨️️","printer","printer"],
      ["⌨️","keyboard","keyboard"],
      ["🖱️","computer mouse","computer_mouse"],
      ["💽","computer disk","minidisc"],
      ["💾","floppy disk","floppy_disk"],
      ["💿","optical disk","cd"],
      ["🧮","abacus","abacus"],
      ["🎥","movie camera","movie_camera"],
      ["🎬","clapper board","clapper"],
      ["📺","television","tv"],
      ["📷","camera","camera"],
      ["📸","camera with flash","camera_flash"],
      ["📹","video camera","video_camera"],
      ["🔍","magnifying glass tilted left","mag"],
      ["🔎","magnifying glass tilted right","mag_right"],
      ["💡","light bulb","bulb"],
      ["🔦","flashlight","flashlight"],
      ["📔","notebook with decorative cover","notebook_with_decorative_cover"],
      ["📕","closed book","closed_book"],
      ["📖","open book","book|open_book"],
      ["📗","green book","green_book"],
      ["📘","blue book","blue_book"],
      ["📙","orange book","orange_book"],
      ["📚","books","books"],
      ["📓","notebook","notebook"],
      ["📒","ledger","ledger"],
      ["📃","page with curl","page_with_curl"],
      ["📜","scroll","scroll"],
      ["📄","page facing up","page_facing_up"],
      ["📰","newspaper","newspaper"],
      ["📑","bookmark tabs","bookmark_tabs"],
      ["🔖","bookmark","bookmark"],
      ["🏷️","label","label"],
      ["💰","money bag","moneybag"],
      ["🪙","coin","coin"],
      ["💵","dollar banknote","dollar"],
      ["💶","euro banknote","euro"],
      ["💷","pound banknote","pound"],
      ["💳","credit card","credit_card"],
      ["🧾","receipt","receipt"],
      ["💹","chart increasing with yen","chart"],
      ["✉️","envelope","envelope"],
      ["📧","e-mail","email|e-mail"],
      ["📨","incoming envelope","incoming_envelope"],
      ["📩","envelope with arrow","envelope_with_arrow"],
      ["📤","outbox tray","outbox_tray"],
      ["📥","inbox tray","inbox_tray"],
      ["📦","package","package"],
      ["📫","closed mailbox with raised flag","mailbox"],
      ["📪","closed mailbox with lowered flag","mailbox_closed"],
      ["📬","open mailbox with raised flag","mailbox_with_mail"],
      ["📭","open mailbox with lowered flag","mailbox_with_no_mail"],
      ["📮","postbox","postbox"],
      ["🗳️","ballot box with ballot","ballot_box"],
      ["✏️","pencil","pencil2"],
      ["✒️","black nib","black_nib"],
      ["🖋️","fountain pen","fountain_pen"],
      ["🖊️","pen","pen"],
      ["🖌️","paintbrush","paintbrush"],
      ["📝","memo","memo|pencil"],
      ["💼","briefcase","briefcase"],
      ["📁","file folder","file_folder"],
      ["📂","open file folder","open_file_folder"],
      ["🗂️","card index dividers","card_index_dividers"],
      ["📅","calendar","date"],
      ["📆","tear-off calendar","calendar"],
      ["🗒️","spiral notepad","spiral_notepad"],
      ["🗓️","spiral calendar","spiral_calendar"],
      ["📇","card index","card_index"],
      ["📈","chart increasing","chart_with_upwards_trend"],
      ["📉","chart decreasing","chart_with_downwards_trend"],
      ["📊","bar chart","bar_chart"],
      ["📋","clipboard","clipboard"],
      ["📌","pushpin","pushpin"],
      ["📍","round pushpin","round_pushpin"],
      ["📎","paperclip","paperclip"],
      ["🖇️","linked paperclips","paperclips"],
      ["📏","straight ruler","straight_ruler"],
      ["📐","triangular ruler","triangular_ruler"],
      ["✂️","scissors","scissors"],
      ["🗃️","card file box","card_file_box"],
      ["🗄️","file cabinet","file_cabinet"],
      ["🗑️","wastebasket","wastebasket"],
      ["🔒","locked","lock"],
      ["🔓","unlocked","unlock"],
      ["🔏","locked with pen","lock_with_ink_pen"],
      ["🔐","locked with key","closed_lock_with_key"],
      ["🔑","key","key"],
      ["🗝️","old key","old_key"],
      ["🔨","hammer","hammer"],
      ["⚒️","hammer and pick","hammer_and_pick"],
      ["🛠️","hammer and wrench","hammer_and_wrench"],
      ["🛡️","shield","shield"],
      ["🔧","wrench","wrench"],
      ["🪛","screwdriver","screwdriver"],
      ["🔩","nut and bolt","nut_and_bolt"],
      ["⚙️","gear","gear"],
      ["⚖️","balance scale","balance_scale"],
      ["🔗","link","link"],
      ["⛓️","chains","chains"],
      ["🧰","toolbox","toolbox"],
      ["🧲","magnet","magnet"],
      ["🪜","ladder","ladder"],
      ["⚗️","alembic","alembic"],
      ["🧪","test tube","test_tube"],
      ["🧫","petri dish","petri_dish"],
      ["🧬","dna","dna"],
      ["🔬","microscope","microscope"],
      ["🔭","telescope","telescope"],
      ["📡","satellite antenna","satellite"],
      ["💉","syringe","syringe"],
      ["💊","pill","pill"],
      ["🩹","adhesive bandage","adhesive_bandage"],
      ["🩺","stethoscope","stethoscope"],
      ["🚪","door","door"],
      ["🛗","elevator","elevator"],
      ["🪞","mirror","mirror"],
      ["🪟","window","window"],
      ["🛋️","couch and lamp","couch_and_lamp"],
      ["🪑","chair","chair"],
      ["🧹","broom","broom"],
      ["🧺","basket","basket"],
      ["🧯","fire extinguisher","fire_extinguisher"],
      ["🛒","shopping cart","shopping_cart"],
      ["🪧","placard","placard"],
      ["🪪","identification card","identification_card"]
    ],
  },
  {
    name: "Symbols",
    items: [
      ["🏧","ATM sign","atm"],
      ["🚮","litter in bin sign","put_litter_in_its_place"],
      ["🚰","potable water","potable_water"],
      ["♿","wheelchair symbol","wheelchair"],
      ["🚹","men’s room","mens"],
      ["🚺","women’s room","womens"],
      ["🚻","restroom","restroom"],
      ["🚼","baby symbol","baby_symbol"],
      ["🚾","water closet","wc"],
      ["🛂","passport control","passport_control"],
      ["🛃","customs","customs"],
      ["🛄","baggage claim","baggage_claim"],
      ["🛅","left luggage","left_luggage"],
      ["⚠️","warning","warning"],
      ["🚸","children crossing","children_crossing"],
      ["⛔","no entry","no_entry"],
      ["🚫","prohibited","no_entry_sign"],
      ["🚳","no bicycles","no_bicycles"],
      ["🚭","no smoking","no_smoking"],
      ["🚯","no littering","do_not_litter"],
      ["🚱","non-potable water","non-potable_water"],
      ["🚷","no pedestrians","no_pedestrians"],
      ["📵","no mobile phones","no_mobile_phones"],
      ["☢️","radioactive","radioactive"],
      ["☣️","biohazard","biohazard"],
      ["⬆️","up arrow","arrow_up"],
      ["↗️","up-right arrow","arrow_upper_right"],
      ["➡️","right arrow","arrow_right"],
      ["↘️","down-right arrow","arrow_lower_right"],
      ["⬇️","down arrow","arrow_down"],
      ["↙️","down-left arrow","arrow_lower_left"],
      ["⬅️","left arrow","arrow_left"],
      ["↖️","up-left arrow","arrow_upper_left"],
      ["↕️","up-down arrow","arrow_up_down"],
      ["↔️","left-right arrow","left_right_arrow"],
      ["↩️","right arrow curving left","leftwards_arrow_with_hook"],
      ["↪️","left arrow curving right","arrow_right_hook"],
      ["⤴️","right arrow curving up","arrow_heading_up"],
      ["⤵️","right arrow curving down","arrow_heading_down"],
      ["🔃","clockwise vertical arrows","arrows_clockwise"],
      ["🔄","counterclockwise arrows button","arrows_counterclockwise"],
      ["🔙","BACK arrow","back"],
      ["🔚","END arrow","end"],
      ["🔛","ON! arrow","on"],
      ["🔜","SOON arrow","soon"],
      ["🔝","TOP arrow","top"],
      ["⚛️","atom symbol","atom_symbol"],
      ["🔀","shuffle tracks button","twisted_rightwards_arrows"],
      ["🔁","repeat button","repeat"],
      ["🔂","repeat single button","repeat_one"],
      ["▶️","play button","arrow_forward"],
      ["⏩","fast-forward button","fast_forward"],
      ["⏭️","next track button","next_track_button"],
      ["⏯️","play or pause button","play_or_pause_button"],
      ["◀️","reverse button","arrow_backward"],
      ["⏪","fast reverse button","rewind"],
      ["⏮️","last track button","previous_track_button"],
      ["🔼","upwards button","arrow_up_small"],
      ["⏫","fast up button","arrow_double_up"],
      ["🔽","downwards button","arrow_down_small"],
      ["⏬","fast down button","arrow_double_down"],
      ["⏸️","pause button","pause_button"],
      ["⏹️","stop button","stop_button"],
      ["⏺️","record button","record_button"],
      ["⏏️","eject button","eject_button"],
      ["🔅","dim button","low_brightness"],
      ["🔆","bright button","high_brightness"],
      ["📶","antenna bars","signal_strength"],
      ["🛜","wireless","wireless"],
      ["📳","vibration mode","vibration_mode"],
      ["📴","mobile phone off","mobile_phone_off"],
      ["✖️","multiply","heavy_multiplication_x"],
      ["➕","plus","heavy_plus_sign"],
      ["➖","minus","heavy_minus_sign"],
      ["➗","divide","heavy_division_sign"],
      ["🟰","heavy equals sign","heavy_equals_sign"],
      ["♾️","infinity","infinity"],
      ["‼️","double exclamation mark","bangbang"],
      ["⁉️","exclamation question mark","interrobang"],
      ["❓","red question mark","question"],
      ["❔","white question mark","grey_question"],
      ["❕","white exclamation mark","grey_exclamation"],
      ["❗","red exclamation mark","exclamation|heavy_exclamation_mark"],
      ["〰️","wavy dash","wavy_dash"],
      ["💱","currency exchange","currency_exchange"],
      ["💲","heavy dollar sign","heavy_dollar_sign"],
      ["⚕️","medical symbol","medical_symbol"],
      ["♻️","recycling symbol","recycle"],
      ["⚜️","fleur-de-lis","fleur_de_lis"],
      ["🔰","Japanese symbol for beginner","beginner"],
      ["⭕","hollow red circle","o"],
      ["✅","check mark button","white_check_mark"],
      ["☑️","check box with check","ballot_box_with_check"],
      ["✔️","check mark","heavy_check_mark"],
      ["❌","cross mark","x"],
      ["❎","cross mark button","negative_squared_cross_mark"],
      ["➰","curly loop","curly_loop"],
      ["➿","double curly loop","loop"],
      ["✳️","eight-spoked asterisk","eight_spoked_asterisk"],
      ["❇️","sparkle","sparkle"],
      ["©️","copyright","copyright"],
      ["®️","registered","registered"],
      ["™️","trade mark","tm"],
      ["#️⃣","keycap: #","hash"],
      ["*️⃣","keycap: *","asterisk"],
      ["0️⃣","keycap: 0","zero"],
      ["1️⃣","keycap: 1","one"],
      ["2️⃣","keycap: 2","two"],
      ["3️⃣","keycap: 3","three"],
      ["4️⃣","keycap: 4","four"],
      ["5️⃣","keycap: 5","five"],
      ["6️⃣","keycap: 6","six"],
      ["7️⃣","keycap: 7","seven"],
      ["8️⃣","keycap: 8","eight"],
      ["9️⃣","keycap: 9","nine"],
      ["🔟","keycap: 10","keycap_ten"],
      ["🔠","input latin uppercase","capital_abcd"],
      ["🔡","input latin lowercase","abcd"],
      ["🔢","input numbers","1234"],
      ["🔣","input symbols","symbols"],
      ["🔤","input latin letters","abc"],
      ["🆒","COOL button","cool"],
      ["🆓","FREE button","free"],
      ["ℹ️","information","information_source"],
      ["🆔","ID button","id"],
      ["🆕","NEW button","new"],
      ["🆖","NG button","ng"],
      ["🆗","OK button","ok"],
      ["🅿️","P button","parking"],
      ["🆘","SOS button","sos"],
      ["🆙","UP! button","up"],
      ["🆚","VS button","vs"],
      ["🔴","red circle","red_circle"],
      ["🟠","orange circle","orange_circle"],
      ["🟡","yellow circle","yellow_circle"],
      ["🟢","green circle","green_circle"],
      ["🔵","blue circle","large_blue_circle"],
      ["🟣","purple circle","purple_circle"],
      ["🟤","brown circle","brown_circle"],
      ["⚫","black circle","black_circle"],
      ["⚪","white circle","white_circle"],
      ["🟥","red square","red_square"],
      ["🟧","orange square","orange_square"],
      ["🟨","yellow square","yellow_square"],
      ["🟩","green square","green_square"],
      ["🟦","blue square","blue_square"],
      ["🟪","purple square","purple_square"],
      ["🟫","brown square","brown_square"],
      ["⬛","black large square","black_large_square"],
      ["⬜","white large square","white_large_square"],
      ["◼️","black medium square","black_medium_square"],
      ["◻️","white medium square","white_medium_square"],
      ["◾","black medium-small square","black_medium_small_square"],
      ["◽","white medium-small square","white_medium_small_square"],
      ["▪️","black small square","black_small_square"],
      ["▫️","white small square","white_small_square"],
      ["🔶","large orange diamond","large_orange_diamond"],
      ["🔷","large blue diamond","large_blue_diamond"],
      ["🔸","small orange diamond","small_orange_diamond"],
      ["🔹","small blue diamond","small_blue_diamond"],
      ["🔺","red triangle pointed up","small_red_triangle"],
      ["🔻","red triangle pointed down","small_red_triangle_down"],
      ["💠","diamond with a dot","diamond_shape_with_a_dot_inside"],
      ["🔘","radio button","radio_button"],
      ["🔳","white square button","white_square_button"],
      ["🔲","black square button","black_square_button"]
    ],
  },
  {
    name: "Flags",
    items: [
      ["🏁","chequered flag","checkered_flag"],
      ["🚩","triangular flag","triangular_flag_on_post"],
      ["🎌","crossed flags","crossed_flags"],
      ["🏴","black flag","black_flag"],
      ["🏳️","white flag","white_flag"]
    ],
  },
];