var EMOJI_CATEGORIES = [
  {
    name: "Smileys & Emotion",
    items: [
      ["😀","grinning face","grinning"],
      ["😃","grinning face with big eyes","smiley"],
      ["😄","grinning face with smiling eyes","smile"],
      ["😁","beaming face with smiling eyes","grin"],
      ["😆","grinning squinting face","laughing|satisfied"],
      ["😅","grinning face with sweat","sweat_smile"],
      ["🤣","rolling on the floor laughing","rofl"],
      ["😂","face with tears of joy","joy"],
      ["🙂","slightly smiling face","slightly_smiling_face"],
      ["🙃","upside-down face","upside_down_face"],
      ["🫠","melting face","melting_face"],
      ["😉","winking face","wink"],
      ["😊","smiling face with smiling eyes","blush"],
      ["😇","smiling face with halo","innocent"],
      ["🥰","smiling face with hearts","smiling_face_with_three_hearts"],
      ["😍","smiling face with heart-eyes","heart_eyes"],
      ["🤩","star-struck","star_struck"],
      ["😘","face blowing a kiss","kissing_heart"],
      ["😗","kissing face","kissing"],
      ["☺️","smiling face","relaxed"],
      ["😚","kissing face with closed eyes","kissing_closed_eyes"],
      ["😙","kissing face with smiling eyes","kissing_smiling_eyes"],
      ["🥲","smiling face with tear","smiling_face_with_tear"],
      ["😋","face savoring food","yum"],
      ["😛","face with tongue","stuck_out_tongue"],
      ["😜","winking face with tongue","stuck_out_tongue_winking_eye"],
      ["🤪","zany face","zany_face"],
      ["😝","squinting face with tongue","stuck_out_tongue_closed_eyes"],
      ["🤑","money-mouth face","money_mouth_face"],
      ["🤗","smiling face with open hands","hugs"],
      ["🤭","face with hand over mouth","hand_over_mouth"],
      ["🫢","face with open eyes and hand over mouth","face_with_open_eyes_and_hand_over_mouth"],
      ["🫣","face with peeking eye","face_with_peeking_eye"],
      ["🤫","shushing face","shushing_face"],
      ["🤔","thinking face","thinking"],
      ["🫡","saluting face","saluting_face"],
      ["🤐","zipper-mouth face","zipper_mouth_face"],
      ["🤨","face with raised eyebrow","raised_eyebrow"],
      ["😐","neutral face","neutral_face"],
      ["😑","expressionless face","expressionless"],
      ["😶","face without mouth","no_mouth"],
      ["🫥","dotted line face","dotted_line_face"],
      ["😶‍🌫️","face in clouds","face_in_clouds"],
      ["😏","smirking face","smirk"],
      ["😒","unamused face","unamused"],
      ["🙄","face with rolling eyes","roll_eyes"],
      ["😬","grimacing face","grimacing"],
      ["😮‍💨","face exhaling","face_exhaling"],
      ["🤥","lying face","lying_face"],
      ["🫨","shaking face","shaking_face"],
      ["😌","relieved face","relieved"],
      ["😔","pensive face","pensive"],
      ["😪","sleepy face","sleepy"],
      ["🤤","drooling face","drooling_face"],
      ["😴","sleeping face","sleeping"],
      ["😷","face with medical mask","mask"],
      ["🤒","face with thermometer","face_with_thermometer"],
      ["🤕","face with head-bandage","face_with_head_bandage"],
      ["🤢","nauseated face","nauseated_face"],
      ["🤮","face vomiting","vomiting_face"],
      ["🤧","sneezing face","sneezing_face"],
      ["🥵","hot face","hot_face"],
      ["🥶","cold face","cold_face"],
      ["🥴","woozy face","woozy_face"],
      ["😵","face with crossed-out eyes","dizzy_face"],
      ["😵‍💫","face with spiral eyes","face_with_spiral_eyes"],
      ["🤯","exploding head","exploding_head"],
      ["🤠","cowboy hat face","cowboy_hat_face"],
      ["🥳","partying face","partying_face"],
      ["🥸","disguised face","disguised_face"],
      ["😎","smiling face with sunglasses","sunglasses"],
      ["🤓","nerd face","nerd_face"],
      ["🧐","face with monocle","monocle_face"],
      ["😕","confused face","confused"],
      ["🫤","face with diagonal mouth","face_with_diagonal_mouth"],
      ["😟","worried face","worried"],
      ["🙁","slightly frowning face","slightly_frowning_face"],
      ["☹️","frowning face","frowning_face"],
      ["😮","face with open mouth","open_mouth"],
      ["😯","hushed face","hushed"],
      ["😲","astonished face","astonished"],
      ["😳","flushed face","flushed"],
      ["🥺","pleading face","pleading_face"],
      ["🥹","face holding back tears","face_holding_back_tears"],
      ["😦","frowning face with open mouth","frowning"],
      ["😧","anguished face","anguished"],
      ["😨","fearful face","fearful"],
      ["😰","anxious face with sweat","cold_sweat"],
      ["😥","sad but relieved face","disappointed_relieved"],
      ["😢","crying face","cry"],
      ["😭","loudly crying face","sob"],
      ["😱","face screaming in fear","scream"],
      ["😖","confounded face","confounded"],
      ["😣","persevering face","persevere"],
      ["😞","disappointed face","disappointed"],
      ["😓","downcast face with sweat","sweat"],
      ["😩","weary face","weary"],
      ["😫","tired face","tired_face"],
      ["🥱","yawning face","yawning_face"],
      ["😤","face with steam from nose","triumph"],
      ["😡","enraged face","rage|pout"],
      ["😠","angry face","angry"],
      ["🤬","face with symbols on mouth","cursing_face"],
      ["😈","smiling face with horns","smiling_imp"],
      ["👿","angry face with horns","imp"],
      ["💀","skull","skull"],
      ["☠️","skull and crossbones","skull_and_crossbones"],
      ["💩","pile of poo","hankey|poop|shit"],
      ["🤡","clown face","clown_face"],
      ["👹","ogre","japanese_ogre"],
      ["👺","goblin","japanese_goblin"],
      ["👻","ghost","ghost"],
      ["👽","alien","alien"],
      ["👾","alien monster","space_invader"],
      ["🤖","robot","robot"],
      ["😺","grinning cat","smiley_cat"],
      ["😸","grinning cat with smiling eyes","smile_cat"],
      ["😹","cat with tears of joy","joy_cat"],
      ["😻","smiling cat with heart-eyes","heart_eyes_cat"],
      ["😼","cat with wry smile","smirk_cat"],
      ["😽","kissing cat","kissing_cat"],
      ["🙀","weary cat","scream_cat"],
      ["😿","crying cat","crying_cat_face"],
      ["😾","pouting cat","pouting_cat"],
      ["🙈","see-no-evil monkey","see_no_evil"],
      ["🙉","hear-no-evil monkey","hear_no_evil"],
      ["🙊","speak-no-evil monkey","speak_no_evil"],
      ["💌","love letter","love_letter"],
      ["💘","heart with arrow","cupid"],
      ["💝","heart with ribbon","gift_heart"],
      ["💖","sparkling heart","sparkling_heart"],
      ["💗","growing heart","heartpulse"],
      ["💓","beating heart","heartbeat"],
      ["💞","revolving hearts","revolving_hearts"],
      ["💕","two hearts","two_hearts"],
      ["💟","heart decoration","heart_decoration"],
      ["❣️","heart exclamation","heavy_heart_exclamation"],
      ["💔","broken heart","broken_heart"],
      ["❤️‍🔥","heart on fire","heart_on_fire"],
      ["❤️‍🩹","mending heart","mending_heart"],
      ["❤️","red heart","heart"],
      ["🩷","pink heart","pink_heart"],
      ["🧡","orange heart","orange_heart"],
      ["💛","yellow heart","yellow_heart"],
      ["💚","green heart","green_heart"],
      ["💙","blue heart","blue_heart"],
      ["🩵","light blue heart","light_blue_heart"],
      ["💜","purple heart","purple_heart"],
      ["🤎","brown heart","brown_heart"],
      ["🖤","black heart","black_heart"],
      ["🩶","grey heart","grey_heart"],
      ["🤍","white heart","white_heart"],
      ["💋","kiss mark","kiss"],
      ["💯","hundred points","100"],
      ["💢","anger symbol","anger"],
      ["💥","collision","boom|collision"],
      ["💫","dizzy","dizzy"],
      ["💦","sweat droplets","sweat_drops"],
      ["💨","dashing away","dash"],
      ["🕳️","hole","hole"],
      ["💬","speech balloon","speech_balloon"],
      ["👁️‍🗨️","eye in speech bubble","eye_speech_bubble"],
      ["🗨️","left speech bubble","left_speech_bubble"],
      ["🗯️","right anger bubble","right_anger_bubble"],
      ["💭","thought balloon","thought_balloon"],
      ["💤","ZZZ","zzz"],
    ],
  },
  {
    name: "People & Body",
    items: [
      ["👋","waving hand","wave"],
      ["🤚","raised back of hand","raised_back_of_hand"],
      ["🖐️","hand with fingers splayed","raised_hand_with_fingers_splayed"],
      ["✋","raised hand","hand|raised_hand"],
      ["🖖","vulcan salute","vulcan_salute"],
      ["🫱","rightwards hand","rightwards_hand"],
      ["🫲","leftwards hand","leftwards_hand"],
      ["🫳","palm down hand","palm_down_hand"],
      ["🫴","palm up hand","palm_up_hand"],
      ["🫷","leftwards pushing hand","leftwards_pushing_hand"],
      ["🫸","rightwards pushing hand","rightwards_pushing_hand"],
      ["👌","OK hand","ok_hand"],
      ["🤌","pinched fingers","pinched_fingers"],
      ["🤏","pinching hand","pinching_hand"],
      ["✌️","victory hand","v"],
      ["🤞","crossed fingers","crossed_fingers"],
      ["🫰","hand with index finger and thumb crossed","hand_with_index_finger_and_thumb_crossed"],
      ["🤟","love-you gesture","love_you_gesture"],
      ["🤘","sign of the horns","metal"],
      ["🤙","call me hand","call_me_hand"],
      ["👈","backhand index pointing left","point_left"],
      ["👉","backhand index pointing right","point_right"],
      ["👆","backhand index pointing up","point_up_2"],
      ["🖕","middle finger","middle_finger|fu"],
      ["👇","backhand index pointing down","point_down"],
      ["☝️","index pointing up","point_up"],
      ["🫵","index pointing at the viewer","index_pointing_at_the_viewer"],
      ["👍","thumbs up","+1|thumbsup"],
      ["👎","thumbs down","-1|thumbsdown"],
      ["✊","raised fist","fist_raised|fist"],
      ["👊","oncoming fist","fist_oncoming|facepunch|punch"],
      ["🤛","left-facing fist","fist_left"],
      ["🤜","right-facing fist","fist_right"],
      ["👏","clapping hands","clap"],
      ["🙌","raising hands","raised_hands"],
      ["🫶","heart hands","heart_hands"],
      ["👐","open hands","open_hands"],
      ["🤲","palms up together","palms_up_together"],
      ["🤝","handshake","handshake"],
      ["🙏","folded hands","pray"],
      ["✍️","writing hand","writing_hand"],
      ["💅","nail polish","nail_care"],
      ["🤳","selfie","selfie"],
      ["💪","flexed biceps","muscle"],
      ["🦾","mechanical arm","mechanical_arm"],
      ["🦿","mechanical leg","mechanical_leg"],
      ["🦵","leg","leg"],
      ["🦶","foot","foot"],
      ["👂","ear","ear"],
      ["🦻","ear with hearing aid","ear_with_hearing_aid"],
      ["👃","nose","nose"],
      ["🧠","brain","brain"],
      ["🫀","anatomical heart","anatomical_heart"],
      ["🫁","lungs","lungs"],
      ["🦷","tooth","tooth"],
      ["🦴","bone","bone"],
      ["👀","eyes","eyes"],
      ["👁️","eye","eye"],
      ["👅","tongue","tongue"],
      ["👄","mouth","lips"],
      ["🫦","biting lip","biting_lip"],
      ["👶","baby","baby"],
      ["🧒","child","child"],
      ["👦","boy","boy"],
      ["👧","girl","girl"],
      ["🧑","person","adult"],
      ["👱","person: blond hair","blond_haired_person"],
      ["👨","man","man"],
      ["🧔","person: beard","bearded_person"],
      ["🧔‍♂️","man: beard","man_beard"],
      ["🧔‍♀️","woman: beard","woman_beard"],
      ["👨‍🦰","man: red hair","red_haired_man"],
      ["👨‍🦱","man: curly hair","curly_haired_man"],
      ["👨‍🦳","man: white hair","white_haired_man"],
      ["👨‍🦲","man: bald","bald_man"],
      ["👩","woman","woman"],
      ["👩‍🦰","woman: red hair","red_haired_woman"],
      ["🧑‍🦰","person: red hair","person_red_hair"],
      ["👩‍🦱","woman: curly hair","curly_haired_woman"],
      ["🧑‍🦱","person: curly hair","person_curly_hair"],
      ["👩‍🦳","woman: white hair","white_haired_woman"],
      ["🧑‍🦳","person: white hair","person_white_hair"],
      ["👩‍🦲","woman: bald","bald_woman"],
      ["🧑‍🦲","person: bald","person_bald"],
      ["👱‍♀️","woman: blond hair","blond_haired_woman|blonde_woman"],
      ["👱‍♂️","man: blond hair","blond_haired_man"],
      ["🧓","older person","older_adult"],
      ["👴","old man","older_man"],
      ["👵","old woman","older_woman"],
      ["🙍","person frowning","frowning_person"],
      ["🙍‍♂️","man frowning","frowning_man"],
      ["🙍‍♀️","woman frowning","frowning_woman"],
      ["🙎","person pouting","pouting_face"],
      ["🙎‍♂️","man pouting","pouting_man"],
      ["🙎‍♀️","woman pouting","pouting_woman"],
      ["🙅","person gesturing NO","no_good"],
      ["🙅‍♂️","man gesturing NO","no_good_man|ng_man"],
      ["🙅‍♀️","woman gesturing NO","no_good_woman|ng_woman"],
      ["🙆","person gesturing OK","ok_person"],
      ["🙆‍♂️","man gesturing OK","ok_man"],
      ["🙆‍♀️","woman gesturing OK","ok_woman"],
      ["💁","person tipping hand","tipping_hand_person|information_desk_person"],
      ["💁‍♂️","man tipping hand","tipping_hand_man|sassy_man"],
      ["💁‍♀️","woman tipping hand","tipping_hand_woman|sassy_woman"],
      ["🙋","person raising hand","raising_hand"],
      ["🙋‍♂️","man raising hand","raising_hand_man"],
      ["🙋‍♀️","woman raising hand","raising_hand_woman"],
      ["🧏","deaf person","deaf_person"],
      ["🧏‍♂️","deaf man","deaf_man"],
      ["🧏‍♀️","deaf woman","deaf_woman"],
      ["🙇","person bowing","bow"],
      ["🙇‍♂️","man bowing","bowing_man"],
      ["🙇‍♀️","woman bowing","bowing_woman"],
      ["🤦","person facepalming","facepalm"],
      ["🤦‍♂️","man facepalming","man_facepalming"],
      ["🤦‍♀️","woman facepalming","woman_facepalming"],
      ["🤷","person shrugging","shrug"],
      ["🤷‍♂️","man shrugging","man_shrugging"],
      ["🤷‍♀️","woman shrugging","woman_shrugging"],
      ["🧑‍⚕️","health worker","health_worker"],
      ["👨‍⚕️","man health worker","man_health_worker"],
      ["👩‍⚕️","woman health worker","woman_health_worker"],
      ["🧑‍🎓","student","student"],
      ["👨‍🎓","man student","man_student"],
      ["👩‍🎓","woman student","woman_student"],
      ["🧑‍🏫","teacher","teacher"],
      ["👨‍🏫","man teacher","man_teacher"],
      ["👩‍🏫","woman teacher","woman_teacher"],
      ["🧑‍⚖️","judge","judge"],
      ["👨‍⚖️","man judge","man_judge"],
      ["👩‍⚖️","woman judge","woman_judge"],
      ["🧑‍🌾","farmer","farmer"],
      ["👨‍🌾","man farmer","man_farmer"],
      ["👩‍🌾","woman farmer","woman_farmer"],
      ["🧑‍🍳","cook","cook"],
      ["👨‍🍳","man cook","man_cook"],
      ["👩‍🍳","woman cook","woman_cook"],
      ["🧑‍🔧","mechanic","mechanic"],
      ["👨‍🔧","man mechanic","man_mechanic"],
      ["👩‍🔧","woman mechanic","woman_mechanic"],
      ["🧑‍🏭","factory worker","factory_worker"],
      ["👨‍🏭","man factory worker","man_factory_worker"],
      ["👩‍🏭","woman factory worker","woman_factory_worker"],
      ["🧑‍💼","office worker","office_worker"],
      ["👨‍💼","man office worker","man_office_worker"],
      ["👩‍💼","woman office worker","woman_office_worker"],
      ["🧑‍🔬","scientist","scientist"],
      ["👨‍🔬","man scientist","man_scientist"],
      ["👩‍🔬","woman scientist","woman_scientist"],
      ["🧑‍💻","technologist","technologist"],
      ["👨‍💻","man technologist","man_technologist"],
      ["👩‍💻","woman technologist","woman_technologist"],
      ["🧑‍🎤","singer","singer"],
      ["👨‍🎤","man singer","man_singer"],
      ["👩‍🎤","woman singer","woman_singer"],
      ["🧑‍🎨","artist","artist"],
      ["👨‍🎨","man artist","man_artist"],
      ["👩‍🎨","woman artist","woman_artist"],
      ["🧑‍✈️","pilot","pilot"],
      ["👨‍✈️","man pilot","man_pilot"],
      ["👩‍✈️","woman pilot","woman_pilot"],
      ["🧑‍🚀","astronaut","astronaut"],
      ["👨‍🚀","man astronaut","man_astronaut"],
      ["👩‍🚀","woman astronaut","woman_astronaut"],
      ["🧑‍🚒","firefighter","firefighter"],
      ["👨‍🚒","man firefighter","man_firefighter"],
      ["👩‍🚒","woman firefighter","woman_firefighter"],
      ["👮","police officer","police_officer|cop"],
      ["👮‍♂️","man police officer","policeman"],
      ["👮‍♀️","woman police officer","policewoman"],
      ["🕵️","detective","detective"],
      ["🕵️‍♂️","man detective","male_detective"],
      ["🕵️‍♀️","woman detective","female_detective"],
      ["💂","guard","guard"],
      ["💂‍♂️","man guard","guardsman"],
      ["💂‍♀️","woman guard","guardswoman"],
      ["🥷","ninja","ninja"],
      ["👷","construction worker","construction_worker"],
      ["👷‍♂️","man construction worker","construction_worker_man"],
      ["👷‍♀️","woman construction worker","construction_worker_woman"],
      ["🫅","person with crown","person_with_crown"],
      ["🤴","prince","prince"],
      ["👸","princess","princess"],
      ["👳","person wearing turban","person_with_turban"],
      ["👳‍♂️","man wearing turban","man_with_turban"],
      ["👳‍♀️","woman wearing turban","woman_with_turban"],
      ["👲","person with skullcap","man_with_gua_pi_mao"],
      ["🧕","woman with headscarf","woman_with_headscarf"],
      ["🤵","person in tuxedo","person_in_tuxedo"],
      ["🤵‍♂️","man in tuxedo","man_in_tuxedo"],
      ["🤵‍♀️","woman in tuxedo","woman_in_tuxedo"],
      ["👰","person with veil","person_with_veil"],
      ["👰‍♂️","man with veil","man_with_veil"],
      ["👰‍♀️","woman with veil","woman_with_veil|bride_with_veil"],
      ["🤰","pregnant woman","pregnant_woman"],
      ["🫃","pregnant man","pregnant_man"],
      ["🫄","pregnant person","pregnant_person"],
      ["🤱","breast-feeding","breast_feeding"],
      ["👩‍🍼","woman feeding baby","woman_feeding_baby"],
      ["👨‍🍼","man feeding baby","man_feeding_baby"],
      ["🧑‍🍼","person feeding baby","person_feeding_baby"],
      ["👼","baby angel","angel"],
      ["🎅","Santa Claus","santa"],
      ["🤶","Mrs. Claus","mrs_claus"],
      ["🧑‍🎄","mx claus","mx_claus"],
      ["🦸","superhero","superhero"],
      ["🦸‍♂️","man superhero","superhero_man"],
      ["🦸‍♀️","woman superhero","superhero_woman"],
      ["🦹","supervillain","supervillain"],
      ["🦹‍♂️","man supervillain","supervillain_man"],
      ["🦹‍♀️","woman supervillain","supervillain_woman"],
      ["🧙","mage","mage"],
      ["🧙‍♂️","man mage","mage_man"],
      ["🧙‍♀️","woman mage","mage_woman"],
      ["🧚","fairy","fairy"],
      ["🧚‍♂️","man fairy","fairy_man"],
      ["🧚‍♀️","woman fairy","fairy_woman"],
      ["🧛","vampire","vampire"],
      ["🧛‍♂️","man vampire","vampire_man"],
      ["🧛‍♀️","woman vampire","vampire_woman"],
      ["🧜","merperson","merperson"],
      ["🧜‍♂️","merman","merman"],
      ["🧜‍♀️","mermaid","mermaid"],
      ["🧝","elf","elf"],
      ["🧝‍♂️","man elf","elf_man"],
      ["🧝‍♀️","woman elf","elf_woman"],
      ["🧞","genie","genie"],
      ["🧞‍♂️","man genie","genie_man"],
      ["🧞‍♀️","woman genie","genie_woman"],
      ["🧟","zombie","zombie"],
      ["🧟‍♂️","man zombie","zombie_man"],
      ["🧟‍♀️","woman zombie","zombie_woman"],
      ["🧌","troll","troll"],
      ["💆","person getting massage","massage"],
      ["💆‍♂️","man getting massage","massage_man"],
      ["💆‍♀️","woman getting massage","massage_woman"],
      ["💇","person getting haircut","haircut"],
      ["💇‍♂️","man getting haircut","haircut_man"],
      ["💇‍♀️","woman getting haircut","haircut_woman"],
      ["🚶","person walking","walking"],
      ["🚶‍♂️","man walking","walking_man"],
      ["🚶‍♀️","woman walking","walking_woman"],
      ["🧍","person standing","standing_person"],
      ["🧍‍♂️","man standing","standing_man"],
      ["🧍‍♀️","woman standing","standing_woman"],
      ["🧎","person kneeling","kneeling_person"],
      ["🧎‍♂️","man kneeling","kneeling_man"],
      ["🧎‍♀️","woman kneeling","kneeling_woman"],
      ["🧑‍🦯","person with white cane","person_with_probing_cane"],
      ["👨‍🦯","man with white cane","man_with_probing_cane"],
      ["👩‍🦯","woman with white cane","woman_with_probing_cane"],
      ["🧑‍🦼","person in motorized wheelchair","person_in_motorized_wheelchair"],
      ["👨‍🦼","man in motorized wheelchair","man_in_motorized_wheelchair"],
      ["👩‍🦼","woman in motorized wheelchair","woman_in_motorized_wheelchair"],
      ["🧑‍🦽","person in manual wheelchair","person_in_manual_wheelchair"],
      ["👨‍🦽","man in manual wheelchair","man_in_manual_wheelchair"],
      ["👩‍🦽","woman in manual wheelchair","woman_in_manual_wheelchair"],
      ["🏃","person running","runner|running"],
      ["🏃‍♂️","man running","running_man"],
      ["🏃‍♀️","woman running","running_woman"],
      ["💃","woman dancing","woman_dancing|dancer"],
      ["🕺","man dancing","man_dancing"],
      ["🕴️","person in suit levitating","business_suit_levitating"],
      ["👯","people with bunny ears","dancers"],
      ["👯‍♂️","men with bunny ears","dancing_men"],
      ["👯‍♀️","women with bunny ears","dancing_women"],
      ["🧖","person in steamy room","sauna_person"],
      ["🧖‍♂️","man in steamy room","sauna_man"],
      ["🧖‍♀️","woman in steamy room","sauna_woman"],
      ["🧗","person climbing","climbing"],
      ["🧗‍♂️","man climbing","climbing_man"],
      ["🧗‍♀️","woman climbing","climbing_woman"],
      ["🤺","person fencing","person_fencing"],
      ["🏇","horse racing","horse_racing"],
      ["⛷️","skier","skier"],
      ["🏂","snowboarder","snowboarder"],
      ["🏌️","person golfing","golfing"],
      ["🏌️‍♂️","man golfing","golfing_man"],
      ["🏌️‍♀️","woman golfing","golfing_woman"],
      ["🏄","person surfing","surfer"],
      ["🏄‍♂️","man surfing","surfing_man"],
      ["🏄‍♀️","woman surfing","surfing_woman"],
      ["🚣","person rowing boat","rowboat"],
      ["🚣‍♂️","man rowing boat","rowing_man"],
      ["🚣‍♀️","woman rowing boat","rowing_woman"],
      ["🏊","person swimming","swimmer"],
      ["🏊‍♂️","man swimming","swimming_man"],
      ["🏊‍♀️","woman swimming","swimming_woman"],
      ["⛹️","person bouncing ball","bouncing_ball_person"],
      ["⛹️‍♂️","man bouncing ball","bouncing_ball_man|basketball_man"],
      ["⛹️‍♀️","woman bouncing ball","bouncing_ball_woman|basketball_woman"],
      ["🏋️","person lifting weights","weight_lifting"],
      ["🏋️‍♂️","man lifting weights","weight_lifting_man"],
      ["🏋️‍♀️","woman lifting weights","weight_lifting_woman"],
      ["🚴","person biking","bicyclist"],
      ["🚴‍♂️","man biking","biking_man"],
      ["🚴‍♀️","woman biking","biking_woman"],
      ["🚵","person mountain biking","mountain_bicyclist"],
      ["🚵‍♂️","man mountain biking","mountain_biking_man"],
      ["🚵‍♀️","woman mountain biking","mountain_biking_woman"],
      ["🤸","person cartwheeling","cartwheeling"],
      ["🤸‍♂️","man cartwheeling","man_cartwheeling"],
      ["🤸‍♀️","woman cartwheeling","woman_cartwheeling"],
      ["🤼","people wrestling","wrestling"],
      ["🤼‍♂️","men wrestling","men_wrestling"],
      ["🤼‍♀️","women wrestling","women_wrestling"],
      ["🤽","person playing water polo","water_polo"],
      ["🤽‍♂️","man playing water polo","man_playing_water_polo"],
      ["🤽‍♀️","woman playing water polo","woman_playing_water_polo"],
      ["🤾","person playing handball","handball_person"],
      ["🤾‍♂️","man playing handball","man_playing_handball"],
      ["🤾‍♀️","woman playing handball","woman_playing_handball"],
      ["🤹","person juggling","juggling_person"],
      ["🤹‍♂️","man juggling","man_juggling"],
      ["🤹‍♀️","woman juggling","woman_juggling"],
      ["🧘","person in lotus position","lotus_position"],
      ["🧘‍♂️","man in lotus position","lotus_position_man"],
      ["🧘‍♀️","woman in lotus position","lotus_position_woman"],
      ["🛀","person taking bath","bath"],
      ["🛌","person in bed","sleeping_bed"],
      ["🧑‍🤝‍🧑","people holding hands","people_holding_hands"],
      ["👭","women holding hands","two_women_holding_hands"],
      ["👫","woman and man holding hands","couple"],
      ["👬","men holding hands","two_men_holding_hands"],
      ["💏","kiss","couplekiss"],
      ["👩‍❤️‍💋‍👨","kiss: woman, man","couplekiss_man_woman"],
      ["👨‍❤️‍💋‍👨","kiss: man, man","couplekiss_man_man"],
      ["👩‍❤️‍💋‍👩","kiss: woman, woman","couplekiss_woman_woman"],
      ["💑","couple with heart","couple_with_heart"],
      ["👩‍❤️‍👨","couple with heart: woman, man","couple_with_heart_woman_man"],
      ["👨‍❤️‍👨","couple with heart: man, man","couple_with_heart_man_man"],
      ["👩‍❤️‍👩","couple with heart: woman, woman","couple_with_heart_woman_woman"],
      ["👪","family","family"],
      ["👨‍👩‍👦","family: man, woman, boy","family_man_woman_boy"],
      ["👨‍👩‍👧","family: man, woman, girl","family_man_woman_girl"],
      ["👨‍👩‍👧‍👦","family: man, woman, girl, boy","family_man_woman_girl_boy"],
      ["👨‍👩‍👦‍👦","family: man, woman, boy, boy","family_man_woman_boy_boy"],
      ["👨‍👩‍👧‍👧","family: man, woman, girl, girl","family_man_woman_girl_girl"],
      ["👨‍👨‍👦","family: man, man, boy","family_man_man_boy"],
      ["👨‍👨‍👧","family: man, man, girl","family_man_man_girl"],
      ["👨‍👨‍👧‍👦","family: man, man, girl, boy","family_man_man_girl_boy"],
      ["👨‍👨‍👦‍👦","family: man, man, boy, boy","family_man_man_boy_boy"],
      ["👨‍👨‍👧‍👧","family: man, man, girl, girl","family_man_man_girl_girl"],
      ["👩‍👩‍👦","family: woman, woman, boy","family_woman_woman_boy"],
      ["👩‍👩‍👧","family: woman, woman, girl","family_woman_woman_girl"],
      ["👩‍👩‍👧‍👦","family: woman, woman, girl, boy","family_woman_woman_girl_boy"],
      ["👩‍👩‍👦‍👦","family: woman, woman, boy, boy","family_woman_woman_boy_boy"],
      ["👩‍👩‍👧‍👧","family: woman, woman, girl, girl","family_woman_woman_girl_girl"],
      ["👨‍👦","family: man, boy","family_man_boy"],
      ["👨‍👦‍👦","family: man, boy, boy","family_man_boy_boy"],
      ["👨‍👧","family: man, girl","family_man_girl"],
      ["👨‍👧‍👦","family: man, girl, boy","family_man_girl_boy"],
      ["👨‍👧‍👧","family: man, girl, girl","family_man_girl_girl"],
      ["👩‍👦","family: woman, boy","family_woman_boy"],
      ["👩‍👦‍👦","family: woman, boy, boy","family_woman_boy_boy"],
      ["👩‍👧","family: woman, girl","family_woman_girl"],
      ["👩‍👧‍👦","family: woman, girl, boy","family_woman_girl_boy"],
      ["👩‍👧‍👧","family: woman, girl, girl","family_woman_girl_girl"],
      ["🗣️","speaking head","speaking_head"],
      ["👤","bust in silhouette","bust_in_silhouette"],
      ["👥","busts in silhouette","busts_in_silhouette"],
      ["🫂","people hugging","people_hugging"],
      ["👣","footprints","footprints"],
    ],
  },
  {
    name: "Animals & Nature",
    items: [
      ["🐵","monkey face","monkey_face"],
      ["🐒","monkey","monkey"],
      ["🦍","gorilla","gorilla"],
      ["🦧","orangutan","orangutan"],
      ["🐶","dog face","dog"],
      ["🐕","dog","dog2"],
      ["🦮","guide dog","guide_dog"],
      ["🐕‍🦺","service dog","service_dog"],
      ["🐩","poodle","poodle"],
      ["🐺","wolf","wolf"],
      ["🦊","fox","fox_face"],
      ["🦝","raccoon","raccoon"],
      ["🐱","cat face","cat"],
      ["🐈","cat","cat2"],
      ["🐈‍⬛","black cat","black_cat"],
      ["🦁","lion","lion"],
      ["🐯","tiger face","tiger"],
      ["🐅","tiger","tiger2"],
      ["🐆","leopard","leopard"],
      ["🐴","horse face","horse"],
      ["🫎","moose","moose"],
      ["🫏","donkey","donkey"],
      ["🐎","horse","racehorse"],
      ["🦄","unicorn","unicorn"],
      ["🦓","zebra","zebra"],
      ["🦌","deer","deer"],
      ["🦬","bison","bison"],
      ["🐮","cow face","cow"],
      ["🐂","ox","ox"],
      ["🐃","water buffalo","water_buffalo"],
      ["🐄","cow","cow2"],
      ["🐷","pig face","pig"],
      ["🐖","pig","pig2"],
      ["🐗","boar","boar"],
      ["🐽","pig nose","pig_nose"],
      ["🐏","ram","ram"],
      ["🐑","ewe","sheep"],
      ["🐐","goat","goat"],
      ["🐪","camel","dromedary_camel"],
      ["🐫","two-hump camel","camel"],
      ["🦙","llama","llama"],
      ["🦒","giraffe","giraffe"],
      ["🐘","elephant","elephant"],
      ["🦣","mammoth","mammoth"],
      ["🦏","rhinoceros","rhinoceros"],
      ["🦛","hippopotamus","hippopotamus"],
      ["🐭","mouse face","mouse"],
      ["🐁","mouse","mouse2"],
      ["🐀","rat","rat"],
      ["🐹","hamster","hamster"],
      ["🐰","rabbit face","rabbit"],
      ["🐇","rabbit","rabbit2"],
      ["🐿️","chipmunk","chipmunk"],
      ["🦫","beaver","beaver"],
      ["🦔","hedgehog","hedgehog"],
      ["🦇","bat","bat"],
      ["🐻","bear","bear"],
      ["🐻‍❄️","polar bear","polar_bear"],
      ["🐨","koala","koala"],
      ["🐼","panda","panda_face"],
      ["🦥","sloth","sloth"],
      ["🦦","otter","otter"],
      ["🦨","skunk","skunk"],
      ["🦘","kangaroo","kangaroo"],
      ["🦡","badger","badger"],
      ["🐾","paw prints","feet|paw_prints"],
      ["🦃","turkey","turkey"],
      ["🐔","chicken","chicken"],
      ["🐓","rooster","rooster"],
      ["🐣","hatching chick","hatching_chick"],
      ["🐤","baby chick","baby_chick"],
      ["🐥","front-facing baby chick","hatched_chick"],
      ["🐦","bird","bird"],
      ["🐧","penguin","penguin"],
      ["🕊️","dove","dove"],
      ["🦅","eagle","eagle"],
      ["🦆","duck","duck"],
      ["🦢","swan","swan"],
      ["🦉","owl","owl"],
      ["🦤","dodo","dodo"],
      ["🪶","feather","feather"],
      ["🦩","flamingo","flamingo"],
      ["🦚","peacock","peacock"],
      ["🦜","parrot","parrot"],
      ["🪽","wing","wing"],
      ["🐦‍⬛","black bird","black_bird"],
      ["���","goose","goose"],
      ["🐸","frog","frog"],
      ["🐊","crocodile","crocodile"],
      ["🐢","turtle","turtle"],
      ["🦎","lizard","lizard"],
      ["🐍","snake","snake"],
      ["🐲","dragon face","dragon_face"],
      ["🐉","dragon","dragon"],
      ["🦕","sauropod","sauropod"],
      ["🦖","T-Rex","t-rex"],
      ["🐳","spouting whale","whale"],
      ["🐋","whale","whale2"],
      ["🐬","dolphin","dolphin|flipper"],
      ["🦭","seal","seal"],
      ["🐟","fish","fish"],
      ["🐠","tropical fish","tropical_fish"],
      ["🐡","blowfish","blowfish"],
      ["🦈","shark","shark"],
      ["🐙","octopus","octopus"],
      ["🐚","spiral shell","shell"],
      ["🪸","coral","coral"],
      ["🪼","jellyfish","jellyfish"],
      ["🐌","snail","snail"],
      ["🦋","butterfly","butterfly"],
      ["🐛","bug","bug"],
      ["🐜","ant","ant"],
      ["🐝","honeybee","bee|honeybee"],
      ["🪲","beetle","beetle"],
      ["🐞","lady beetle","lady_beetle"],
      ["🦗","cricket","cricket"],
      ["🪳","cockroach","cockroach"],
      ["🕷️","spider","spider"],
      ["🕸️","spider web","spider_web"],
      ["🦂","scorpion","scorpion"],
      ["🦟","mosquito","mosquito"],
      ["🪰","fly","fly"],
      ["🪱","worm","worm"],
      ["🦠","microbe","microbe"],
      ["💐","bouquet","bouquet"],
      ["🌸","cherry blossom","cherry_blossom"],
      ["💮","white flower","white_flower"],
      ["🪷","lotus","lotus"],
      ["🏵️","rosette","rosette"],
      ["🌹","rose","rose"],
      ["🥀","wilted flower","wilted_flower"],
      ["🌺","hibiscus","hibiscus"],
      ["🌻","sunflower","sunflower"],
      ["🌼","blossom","blossom"],
      ["🌷","tulip","tulip"],
      ["🪻","hyacinth","hyacinth"],
      ["🌱","seedling","seedling"],
      ["🪴","potted plant","potted_plant"],
      ["🌲","evergreen tree","evergreen_tree"],
      ["🌳","deciduous tree","deciduous_tree"],
      ["🌴","palm tree","palm_tree"],
      ["🌵","cactus","cactus"],
      ["🌾","sheaf of rice","ear_of_rice"],
      ["🌿","herb","herb"],
      ["☘️","shamrock","shamrock"],
      ["🍀","four leaf clover","four_leaf_clover"],
      ["🍁","maple leaf","maple_leaf"],
      ["🍂","fallen leaf","fallen_leaf"],
      ["🍃","leaf fluttering in wind","leaves"],
      ["🪹","empty nest","empty_nest"],
      ["🪺","nest with eggs","nest_with_eggs"],
      ["🍄","mushroom","mushroom"],
    ],
  },
  {
    name: "Food & Drink",
    items: [
      ["🍇","grapes","grapes"],
      ["🍈","melon","melon"],
      ["🍉","watermelon","watermelon"],
      ["🍊","tangerine","tangerine|orange|mandarin"],
      ["🍋","lemon","lemon"],
      ["🍌","banana","banana"],
      ["🍍","pineapple","pineapple"],
      ["🥭","mango","mango"],
      ["🍎","red apple","apple"],
      ["🍏","green apple","green_apple"],
      ["🍐","pear","pear"],
      ["🍑","peach","peach"],
      ["🍒","cherries","cherries"],
      ["🍓","strawberry","strawberry"],
      ["🫐","blueberries","blueberries"],
      ["🥝","kiwi fruit","kiwi_fruit"],
      ["🍅","tomato","tomato"],
      ["🫒","olive","olive"],
      ["🥥","coconut","coconut"],
      ["🥑","avocado","avocado"],
      ["🍆","eggplant","eggplant"],
      ["🥔","potato","potato"],
      ["🥕","carrot","carrot"],
      ["🌽","ear of corn","corn"],
      ["🌶️","hot pepper","hot_pepper"],
      ["🫑","bell pepper","bell_pepper"],
      ["🥒","cucumber","cucumber"],
      ["🥬","leafy green","leafy_green"],
      ["🥦","broccoli","broccoli"],
      ["🧄","garlic","garlic"],
      ["🧅","onion","onion"],
      ["🥜","peanuts","peanuts"],
      ["🫘","beans","beans"],
      ["🌰","chestnut","chestnut"],
      ["🫚","ginger root","ginger_root"],
      ["🫛","pea pod","pea_pod"],
      ["🍞","bread","bread"],
      ["🥐","croissant","croissant"],
      ["🥖","baguette bread","baguette_bread"],
      ["🫓","flatbread","flatbread"],
      ["🥨","pretzel","pretzel"],
      ["🥯","bagel","bagel"],
      ["🥞","pancakes","pancakes"],
      ["🧇","waffle","waffle"],
      ["🧀","cheese wedge","cheese"],
      ["🍖","meat on bone","meat_on_bone"],
      ["🍗","poultry leg","poultry_leg"],
      ["🥩","cut of meat","cut_of_meat"],
      ["🥓","bacon","bacon"],
      ["🍔","hamburger","hamburger"],
      ["🍟","french fries","fries"],
      ["🍕","pizza","pizza"],
      ["🌭","hot dog","hotdog"],
      ["🥪","sandwich","sandwich"],
      ["🌮","taco","taco"],
      ["🌯","burrito","burrito"],
      ["🫔","tamale","tamale"],
      ["🥙","stuffed flatbread","stuffed_flatbread"],
      ["🧆","falafel","falafel"],
      ["🥚","egg","egg"],
      ["🍳","cooking","fried_egg"],
      ["🥘","shallow pan of food","shallow_pan_of_food"],
      ["🍲","pot of food","stew"],
      ["🫕","fondue","fondue"],
      ["🥣","bowl with spoon","bowl_with_spoon"],
      ["🥗","green salad","green_salad"],
      ["🍿","popcorn","popcorn"],
      ["🧈","butter","butter"],
      ["🧂","salt","salt"],
      ["🥫","canned food","canned_food"],
      ["🍱","bento box","bento"],
      ["🍘","rice cracker","rice_cracker"],
      ["🍙","rice ball","rice_ball"],
      ["🍚","cooked rice","rice"],
      ["🍛","curry rice","curry"],
      ["🍜","steaming bowl","ramen"],
      ["🍝","spaghetti","spaghetti"],
      ["🍠","roasted sweet potato","sweet_potato"],
      ["🍢","oden","oden"],
      ["🍣","sushi","sushi"],
      ["🍤","fried shrimp","fried_shrimp"],
      ["🍥","fish cake with swirl","fish_cake"],
      ["🥮","moon cake","moon_cake"],
      ["🍡","dango","dango"],
      ["🥟","dumpling","dumpling"],
      ["🥠","fortune cookie","fortune_cookie"],
      ["🥡","takeout box","takeout_box"],
      ["🦀","crab","crab"],
      ["🦞","lobster","lobster"],
      ["🦐","shrimp","shrimp"],
      ["🦑","squid","squid"],
      ["🦪","oyster","oyster"],
      ["🍦","soft ice cream","icecream"],
      ["🍧","shaved ice","shaved_ice"],
      ["🍨","ice cream","ice_cream"],
      ["🍩","doughnut","doughnut"],
      ["🍪","cookie","cookie"],
      ["🎂","birthday cake","birthday"],
      ["🍰","shortcake","cake"],
      ["🧁","cupcake","cupcake"],
      ["🥧","pie","pie"],
      ["🍫","chocolate bar","chocolate_bar"],
      ["🍬","candy","candy"],
      ["🍭","lollipop","lollipop"],
      ["🍮","custard","custard"],
      ["🍯","honey pot","honey_pot"],
      ["🍼","baby bottle","baby_bottle"],
      ["🥛","glass of milk","milk_glass"],
      ["☕","hot beverage","coffee"],
      ["🫖","teapot","teapot"],
      ["🍵","teacup without handle","tea"],
      ["🍶","sake","sake"],
      ["🍾","bottle with popping cork","champagne"],
      ["🍷","wine glass","wine_glass"],
      ["🍸","cocktail glass","cocktail"],
      ["🍹","tropical drink","tropical_drink"],
      ["🍺","beer mug","beer"],
      ["🍻","clinking beer mugs","beers"],
      ["🥂","clinking glasses","clinking_glasses"],
      ["🥃","tumbler glass","tumbler_glass"],
      ["🫗","pouring liquid","pouring_liquid"],
      ["🥤","cup with straw","cup_with_straw"],
      ["🧋","bubble tea","bubble_tea"],
      ["🧃","beverage box","beverage_box"],
      ["🧉","mate","mate"],
      ["🧊","ice","ice_cube"],
      ["🥢","chopsticks","chopsticks"],
      ["🍽️","fork and knife with plate","plate_with_cutlery"],
      ["🍴","fork and knife","fork_and_knife"],
      ["🥄","spoon","spoon"],
      ["🔪","kitchen knife","hocho|knife"],
      ["🫙","jar","jar"],
      ["🏺","amphora","amphora"],
    ],
  },
  {
    name: "Travel & Places",
    items: [
      ["🌍","globe showing Europe-Africa","earth_africa"],
      ["🌎","globe showing Americas","earth_americas"],
      ["🌏","globe showing Asia-Australia","earth_asia"],
      ["🌐","globe with meridians","globe_with_meridians"],
      ["🗺️","world map","world_map"],
      ["🗾","map of Japan","japan"],
      ["🧭","compass","compass"],
      ["🏔️","snow-capped mountain","mountain_snow"],
      ["⛰️","mountain","mountain"],
      ["🌋","volcano","volcano"],
      ["🗻","mount fuji","mount_fuji"],
      ["🏕️","camping","camping"],
      ["🏖️","beach with umbrella","beach_umbrella"],
      ["🏜️","desert","desert"],
      ["🏝️","desert island","desert_island"],
      ["🏞️","national park","national_park"],
      ["🏟️","stadium","stadium"],
      ["🏛️","classical building","classical_building"],
      ["🏗️","building construction","building_construction"],
      ["🧱","brick","bricks"],
      ["🪨","rock","rock"],
      ["🪵","wood","wood"],
      ["🛖","hut","hut"],
      ["🏘️","houses","houses"],
      ["🏚️","derelict house","derelict_house"],
      ["🏠","house","house"],
      ["🏡","house with garden","house_with_garden"],
      ["🏢","office building","office"],
      ["🏣","Japanese post office","post_office"],
      ["🏤","post office","european_post_office"],
      ["🏥","hospital","hospital"],
      ["🏦","bank","bank"],
      ["🏨","hotel","hotel"],
      ["🏩","love hotel","love_hotel"],
      ["🏪","convenience store","convenience_store"],
      ["🏫","school","school"],
      ["🏬","department store","department_store"],
      ["🏭","factory","factory"],
      ["🏯","Japanese castle","japanese_castle"],
      ["🏰","castle","european_castle"],
      ["💒","wedding","wedding"],
      ["🗼","Tokyo tower","tokyo_tower"],
      ["🗽","Statue of Liberty","statue_of_liberty"],
      ["⛪","church","church"],
      ["🕌","mosque","mosque"],
      ["🛕","hindu temple","hindu_temple"],
      ["🕍","synagogue","synagogue"],
      ["⛩️","shinto shrine","shinto_shrine"],
      ["🕋","kaaba","kaaba"],
      ["⛲","fountain","fountain"],
      ["⛺","tent","tent"],
      ["🌁","foggy","foggy"],
      ["🌃","night with stars","night_with_stars"],
      ["🏙️","cityscape","cityscape"],
      ["🌄","sunrise over mountains","sunrise_over_mountains"],
      ["🌅","sunrise","sunrise"],
      ["🌆","cityscape at dusk","city_sunset"],
      ["🌇","sunset","city_sunrise"],
      ["🌉","bridge at night","bridge_at_night"],
      ["♨️","hot springs","hotsprings"],
      ["🎠","carousel horse","carousel_horse"],
      ["🛝","playground slide","playground_slide"],
      ["🎡","ferris wheel","ferris_wheel"],
      ["🎢","roller coaster","roller_coaster"],
      ["💈","barber pole","barber"],
      ["🎪","circus tent","circus_tent"],
      ["🚂","locomotive","steam_locomotive"],
      ["🚃","railway car","railway_car"],
      ["🚄","high-speed train","bullettrain_side"],
      ["🚅","bullet train","bullettrain_front"],
      ["🚆","train","train2"],
      ["🚇","metro","metro"],
      ["🚈","light rail","light_rail"],
      ["🚉","station","station"],
      ["🚊","tram","tram"],
      ["🚝","monorail","monorail"],
      ["🚞","mountain railway","mountain_railway"],
      ["🚋","tram car","train"],
      ["🚌","bus","bus"],
      ["🚍","oncoming bus","oncoming_bus"],
      ["🚎","trolleybus","trolleybus"],
      ["🚐","minibus","minibus"],
      ["🚑","ambulance","ambulance"],
      ["🚒","fire engine","fire_engine"],
      ["🚓","police car","police_car"],
      ["🚔","oncoming police car","oncoming_police_car"],
      ["🚕","taxi","taxi"],
      ["🚖","oncoming taxi","oncoming_taxi"],
      ["🚗","automobile","car|red_car"],
      ["🚘","oncoming automobile","oncoming_automobile"],
      ["🚙","sport utility vehicle","blue_car"],
      ["🛻","pickup truck","pickup_truck"],
      ["🚚","delivery truck","truck"],
      ["🚛","articulated lorry","articulated_lorry"],
      ["🚜","tractor","tractor"],
      ["🏎️","racing car","racing_car"],
      ["🏍️","motorcycle","motorcycle"],
      ["🛵","motor scooter","motor_scooter"],
      ["🦽","manual wheelchair","manual_wheelchair"],
      ["🦼","motorized wheelchair","motorized_wheelchair"],
      ["🛺","auto rickshaw","auto_rickshaw"],
      ["🚲","bicycle","bike"],
      ["🛴","kick scooter","kick_scooter"],
      ["🛹","skateboard","skateboard"],
      ["🛼","roller skate","roller_skate"],
      ["🚏","bus stop","busstop"],
      ["🛣️","motorway","motorway"],
      ["🛤️","railway track","railway_track"],
      ["🛢️","oil drum","oil_drum"],
      ["⛽","fuel pump","fuelpump"],
      ["🛞","wheel","wheel"],
      ["🚨","police car light","rotating_light"],
      ["🚥","horizontal traffic light","traffic_light"],
      ["🚦","vertical traffic light","vertical_traffic_light"],
      ["🛑","stop sign","stop_sign"],
      ["🚧","construction","construction"],
      ["⚓","anchor","anchor"],
      ["🛟","ring buoy","ring_buoy"],
      ["⛵","sailboat","boat|sailboat"],
      ["🛶","canoe","canoe"],
      ["🚤","speedboat","speedboat"],
      ["🛳️","passenger ship","passenger_ship"],
      ["⛴️","ferry","ferry"],
      ["🛥️","motor boat","motor_boat"],
      ["🚢","ship","ship"],
      ["✈️","airplane","airplane"],
      ["🛩️","small airplane","small_airplane"],
      ["🛫","airplane departure","flight_departure"],
      ["🛬","airplane arrival","flight_arrival"],
      ["🪂","parachute","parachute"],
      ["💺","seat","seat"],
      ["🚁","helicopter","helicopter"],
      ["🚟","suspension railway","suspension_railway"],
      ["🚠","mountain cableway","mountain_cableway"],
      ["🚡","aerial tramway","aerial_tramway"],
      ["🛰️","satellite","artificial_satellite"],
      ["🚀","rocket","rocket"],
      ["🛸","flying saucer","flying_saucer"],
      ["🛎️","bellhop bell","bellhop_bell"],
      ["🧳","luggage","luggage"],
      ["⌛","hourglass done","hourglass"],
      ["⏳","hourglass not done","hourglass_flowing_sand"],
      ["⌚","watch","watch"],
      ["⏰","alarm clock","alarm_clock"],
      ["⏱️","stopwatch","stopwatch"],
      ["⏲️","timer clock","timer_clock"],
      ["🕰️","mantelpiece clock","mantelpiece_clock"],
      ["🕛","twelve o’clock","clock12"],
      ["🕧","twelve-thirty","clock1230"],
      ["🕐","one o’clock","clock1"],
      ["🕜","one-thirty","clock130"],
      ["🕑","two o’clock","clock2"],
      ["🕝","two-thirty","clock230"],
      ["🕒","three o’clock","clock3"],
      ["🕞","three-thirty","clock330"],
      ["🕓","four o’clock","clock4"],
      ["🕟","four-thirty","clock430"],
      ["🕔","five o’clock","clock5"],
      ["🕠","five-thirty","clock530"],
      ["🕕","six o’clock","clock6"],
      ["🕡","six-thirty","clock630"],
      ["🕖","seven o’clock","clock7"],
      ["🕢","seven-thirty","clock730"],
      ["🕗","eight o’clock","clock8"],
      ["🕣","eight-thirty","clock830"],
      ["🕘","nine o’clock","clock9"],
      ["🕤","nine-thirty","clock930"],
      ["🕙","ten o’clock","clock10"],
      ["🕥","ten-thirty","clock1030"],
      ["🕚","eleven o’clock","clock11"],
      ["🕦","eleven-thirty","clock1130"],
      ["🌑","new moon","new_moon"],
      ["🌒","waxing crescent moon","waxing_crescent_moon"],
      ["🌓","first quarter moon","first_quarter_moon"],
      ["🌔","waxing gibbous moon","moon|waxing_gibbous_moon"],
      ["🌕","full moon","full_moon"],
      ["🌖","waning gibbous moon","waning_gibbous_moon"],
      ["🌗","last quarter moon","last_quarter_moon"],
      ["🌘","waning crescent moon","waning_crescent_moon"],
      ["🌙","crescent moon","crescent_moon"],
      ["🌚","new moon face","new_moon_with_face"],
      ["🌛","first quarter moon face","first_quarter_moon_with_face"],
      ["🌜","last quarter moon face","last_quarter_moon_with_face"],
      ["🌡️","thermometer","thermometer"],
      ["☀️","sun","sunny"],
      ["🌝","full moon face","full_moon_with_face"],
      ["🌞","sun with face","sun_with_face"],
      ["🪐","ringed planet","ringed_planet"],
      ["⭐","star","star"],
      ["🌟","glowing star","star2"],
      ["🌠","shooting star","stars"],
      ["🌌","milky way","milky_way"],
      ["☁️","cloud","cloud"],
      ["⛅","sun behind cloud","partly_sunny"],
      ["⛈️","cloud with lightning and rain","cloud_with_lightning_and_rain"],
      ["🌤️","sun behind small cloud","sun_behind_small_cloud"],
      ["🌥️","sun behind large cloud","sun_behind_large_cloud"],
      ["🌦️","sun behind rain cloud","sun_behind_rain_cloud"],
      ["🌧️","cloud with rain","cloud_with_rain"],
      ["🌨️","cloud with snow","cloud_with_snow"],
      ["🌩️","cloud with lightning","cloud_with_lightning"],
      ["🌪️","tornado","tornado"],
      ["🌫️","fog","fog"],
      ["🌬️","wind face","wind_face"],
      ["🌀","cyclone","cyclone"],
      ["🌈","rainbow","rainbow"],
      ["🌂","closed umbrella","closed_umbrella"],
      ["☂️","umbrella","open_umbrella"],
      ["☔","umbrella with rain drops","umbrella"],
      ["⛱️","umbrella on ground","parasol_on_ground"],
      ["⚡","high voltage","zap"],
      ["❄️","snowflake","snowflake"],
      ["☃️","snowman","snowman_with_snow"],
      ["⛄","snowman without snow","snowman"],
      ["☄️","comet","comet"],
      ["🔥","fire","fire"],
      ["💧","droplet","droplet"],
      ["🌊","water wave","ocean"],
    ],
  },
  {
    name: "Activities",
    items: [
      ["🎃","jack-o-lantern","jack_o_lantern"],
      ["🎄","Christmas tree","christmas_tree"],
      ["🎆","fireworks","fireworks"],
      ["🎇","sparkler","sparkler"],
      ["🧨","firecracker","firecracker"],
      ["✨","sparkles","sparkles"],
      ["🎈","balloon","balloon"],
      ["🎉","party popper","tada"],
      ["🎊","confetti ball","confetti_ball"],
      ["🎋","tanabata tree","tanabata_tree"],
      ["🎍","pine decoration","bamboo"],
      ["🎎","Japanese dolls","dolls"],
      ["🎏","carp streamer","flags"],
      ["🎐","wind chime","wind_chime"],
      ["🎑","moon viewing ceremony","rice_scene"],
      ["🧧","red envelope","red_envelope"],
      ["🎀","ribbon","ribbon"],
      ["🎁","wrapped gift","gift"],
      ["🎗️","reminder ribbon","reminder_ribbon"],
      ["🎟️","admission tickets","tickets"],
      ["🎫","ticket","ticket"],
      ["🎖️","military medal","medal_military"],
      ["🏆","trophy","trophy"],
      ["🏅","sports medal","medal_sports"],
      ["🥇","1st place medal","1st_place_medal"],
      ["🥈","2nd place medal","2nd_place_medal"],
      ["🥉","3rd place medal","3rd_place_medal"],
      ["⚽","soccer ball","soccer"],
      ["⚾","baseball","baseball"],
      ["🥎","softball","softball"],
      ["🏀","basketball","basketball"],
      ["🏐","volleyball","volleyball"],
      ["🏈","american football","football"],
      ["🏉","rugby football","rugby_football"],
      ["🎾","tennis","tennis"],
      ["🥏","flying disc","flying_disc"],
      ["🎳","bowling","bowling"],
      ["🏏","cricket game","cricket_game"],
      ["🏑","field hockey","field_hockey"],
      ["🏒","ice hockey","ice_hockey"],
      ["🥍","lacrosse","lacrosse"],
      ["🏓","ping pong","ping_pong"],
      ["🏸","badminton","badminton"],
      ["🥊","boxing glove","boxing_glove"],
      ["🥋","martial arts uniform","martial_arts_uniform"],
      ["🥅","goal net","goal_net"],
      ["⛳","flag in hole","golf"],
      ["⛸️","ice skate","ice_skate"],
      ["🎣","fishing pole","fishing_pole_and_fish"],
      ["🤿","diving mask","diving_mask"],
      ["🎽","running shirt","running_shirt_with_sash"],
      ["🎿","skis","ski"],
      ["🛷","sled","sled"],
      ["🥌","curling stone","curling_stone"],
      ["🎯","bullseye","dart"],
      ["🪀","yo-yo","yo_yo"],
      ["🪁","kite","kite"],
      ["🔫","water pistol","gun"],
      ["🎱","pool 8 ball","8ball"],
      ["🔮","crystal ball","crystal_ball"],
      ["🪄","magic wand","magic_wand"],
      ["🎮","video game","video_game"],
      ["🕹️","joystick","joystick"],
      ["🎰","slot machine","slot_machine"],
      ["🎲","game die","game_die"],
      ["🧩","puzzle piece","jigsaw"],
      ["🧸","teddy bear","teddy_bear"],
      ["🪅","piñata","pinata"],
      ["🪩","mirror ball","mirror_ball"],
      ["🪆","nesting dolls","nesting_dolls"],
      ["♠️","spade suit","spades"],
      ["♥️","heart suit","hearts"],
      ["♦️","diamond suit","diamonds"],
      ["♣️","club suit","clubs"],
      ["♟️","chess pawn","chess_pawn"],
      ["🃏","joker","black_joker"],
      ["🀄","mahjong red dragon","mahjong"],
      ["🎴","flower playing cards","flower_playing_cards"],
      ["🎭","performing arts","performing_arts"],
      ["🖼️","framed picture","framed_picture"],
      ["🎨","artist palette","art"],
      ["🧵","thread","thread"],
      ["🪡","sewing needle","sewing_needle"],
      ["🧶","yarn","yarn"],
      ["🪢","knot","knot"],
    ],
  },
  {
    name: "Objects",
    items: [
      ["👓","glasses","eyeglasses"],
      ["🕶️","sunglasses","dark_sunglasses"],
      ["🥽","goggles","goggles"],
      ["🥼","lab coat","lab_coat"],
      ["🦺","safety vest","safety_vest"],
      ["👔","necktie","necktie"],
      ["👕","t-shirt","shirt|tshirt"],
      ["👖","jeans","jeans"],
      ["🧣","scarf","scarf"],
      ["🧤","gloves","gloves"],
      ["🧥","coat","coat"],
      ["🧦","socks","socks"],
      ["👗","dress","dress"],
      ["👘","kimono","kimono"],
      ["🥻","sari","sari"],
      ["🩱","one-piece swimsuit","one_piece_swimsuit"],
      ["🩲","briefs","swim_brief"],
      ["🩳","shorts","shorts"],
      ["👙","bikini","bikini"],
      ["👚","woman’s clothes","womans_clothes"],
      ["🪭","folding hand fan","folding_hand_fan"],
      ["👛","purse","purse"],
      ["👜","handbag","handbag"],
      ["👝","clutch bag","pouch"],
      ["🛍️","shopping bags","shopping"],
      ["🎒","backpack","school_satchel"],
      ["🩴","thong sandal","thong_sandal"],
      ["👞","man’s shoe","mans_shoe|shoe"],
      ["👟","running shoe","athletic_shoe"],
      ["🥾","hiking boot","hiking_boot"],
      ["🥿","flat shoe","flat_shoe"],
      ["👠","high-heeled shoe","high_heel"],
      ["👡","woman’s sandal","sandal"],
      ["🩰","ballet shoes","ballet_shoes"],
      ["👢","woman’s boot","boot"],
      ["🪮","hair pick","hair_pick"],
      ["👑","crown","crown"],
      ["👒","woman’s hat","womans_hat"],
      ["🎩","top hat","tophat"],
      ["🎓","graduation cap","mortar_board"],
      ["🧢","billed cap","billed_cap"],
      ["🪖","military helmet","military_helmet"],
      ["⛑️","rescue worker’s helmet","rescue_worker_helmet"],
      ["📿","prayer beads","prayer_beads"],
      ["💄","lipstick","lipstick"],
      ["💍","ring","ring"],
      ["💎","gem stone","gem"],
      ["🔇","muted speaker","mute"],
      ["🔈","speaker low volume","speaker"],
      ["🔉","speaker medium volume","sound"],
      ["🔊","speaker high volume","loud_sound"],
      ["📢","loudspeaker","loudspeaker"],
      ["📣","megaphone","mega"],
      ["📯","postal horn","postal_horn"],
      ["🔔","bell","bell"],
      ["🔕","bell with slash","no_bell"],
      ["🎼","musical score","musical_score"],
      ["🎵","musical note","musical_note"],
      ["🎶","musical notes","notes"],
      ["🎙️","studio microphone","studio_microphone"],
      ["🎚️","level slider","level_slider"],
      ["🎛️","control knobs","control_knobs"],
      ["🎤","microphone","microphone"],
      ["🎧","headphone","headphones"],
      ["📻","radio","radio"],
      ["🎷","saxophone","saxophone"],
      ["🪗","accordion","accordion"],
      ["🎸","guitar","guitar"],
      ["🎹","musical keyboard","musical_keyboard"],
      ["🎺","trumpet","trumpet"],
      ["🎻","violin","violin"],
      ["🪕","banjo","banjo"],
      ["🥁","drum","drum"],
      ["🪘","long drum","long_drum"],
      ["🪇","maracas","maracas"],
      ["🪈","flute","flute"],
      ["📱","mobile phone","iphone"],
      ["📲","mobile phone with arrow","calling"],
      ["☎️","telephone","phone|telephone"],
      ["📞","telephone receiver","telephone_receiver"],
      ["📟","pager","pager"],
      ["📠","fax machine","fax"],
      ["🔋","battery","battery"],
      ["🪫","low battery","low_battery"],
      ["🔌","electric plug","electric_plug"],
      ["💻","laptop","computer"],
      ["🖥️","desktop computer","desktop_computer"],
      ["🖨️","printer","printer"],
      ["⌨️","keyboard","keyboard"],
      ["🖱️","computer mouse","computer_mouse"],
      ["🖲️","trackball","trackball"],
      ["💽","computer disk","minidisc"],
      ["💾","floppy disk","floppy_disk"],
      ["💿","optical disk","cd"],
      ["📀","dvd","dvd"],
      ["🧮","abacus","abacus"],
      ["🎥","movie camera","movie_camera"],
      ["🎞️","film frames","film_strip"],
      ["📽️","film projector","film_projector"],
      ["🎬","clapper board","clapper"],
      ["📺","television","tv"],
      ["📷","camera","camera"],
      ["📸","camera with flash","camera_flash"],
      ["📹","video camera","video_camera"],
      ["📼","videocassette","vhs"],
      ["🔍","magnifying glass tilted left","mag"],
      ["🔎","magnifying glass tilted right","mag_right"],
      ["🕯️","candle","candle"],
      ["💡","light bulb","bulb"],
      ["🔦","flashlight","flashlight"],
      ["🏮","red paper lantern","izakaya_lantern|lantern"],
      ["🪔","diya lamp","diya_lamp"],
      ["📔","notebook with decorative cover","notebook_with_decorative_cover"],
      ["📕","closed book","closed_book"],
      ["📖","open book","book|open_book"],
      ["📗","green book","green_book"],
      ["📘","blue book","blue_book"],
      ["📙","orange book","orange_book"],
      ["📚","books","books"],
      ["📓","notebook","notebook"],
      ["📒","ledger","ledger"],
      ["📃","page with curl","page_with_curl"],
      ["📜","scroll","scroll"],
      ["📄","page facing up","page_facing_up"],
      ["📰","newspaper","newspaper"],
      ["🗞️","rolled-up newspaper","newspaper_roll"],
      ["📑","bookmark tabs","bookmark_tabs"],
      ["🔖","bookmark","bookmark"],
      ["🏷️","label","label"],
      ["💰","money bag","moneybag"],
      ["🪙","coin","coin"],
      ["💴","yen banknote","yen"],
      ["💵","dollar banknote","dollar"],
      ["💶","euro banknote","euro"],
      ["💷","pound banknote","pound"],
      ["💸","money with wings","money_with_wings"],
      ["💳","credit card","credit_card"],
      ["🧾","receipt","receipt"],
      ["💹","chart increasing with yen","chart"],
      ["✉️","envelope","envelope"],
      ["📧","e-mail","email|e-mail"],
      ["📨","incoming envelope","incoming_envelope"],
      ["📩","envelope with arrow","envelope_with_arrow"],
      ["📤","outbox tray","outbox_tray"],
      ["📥","inbox tray","inbox_tray"],
      ["📦","package","package"],
      ["📫","closed mailbox with raised flag","mailbox"],
      ["📪","closed mailbox with lowered flag","mailbox_closed"],
      ["📬","open mailbox with raised flag","mailbox_with_mail"],
      ["📭","open mailbox with lowered flag","mailbox_with_no_mail"],
      ["📮","postbox","postbox"],
      ["🗳️","ballot box with ballot","ballot_box"],
      ["✏️","pencil","pencil2"],
      ["✒️","black nib","black_nib"],
      ["🖋️","fountain pen","fountain_pen"],
      ["🖊️","pen","pen"],
      ["🖌️","paintbrush","paintbrush"],
      ["🖍️","crayon","crayon"],
      ["📝","memo","memo|pencil"],
      ["💼","briefcase","briefcase"],
      ["📁","file folder","file_folder"],
      ["📂","open file folder","open_file_folder"],
      ["🗂️","card index dividers","card_index_dividers"],
      ["📅","calendar","date"],
      ["📆","tear-off calendar","calendar"],
      ["🗒️","spiral notepad","spiral_notepad"],
      ["🗓️","spiral calendar","spiral_calendar"],
      ["📇","card index","card_index"],
      ["📈","chart increasing","chart_with_upwards_trend"],
      ["📉","chart decreasing","chart_with_downwards_trend"],
      ["📊","bar chart","bar_chart"],
      ["📋","clipboard","clipboard"],
      ["📌","pushpin","pushpin"],
      ["📍","round pushpin","round_pushpin"],
      ["📎","paperclip","paperclip"],
      ["🖇️","linked paperclips","paperclips"],
      ["📏","straight ruler","straight_ruler"],
      ["📐","triangular ruler","triangular_ruler"],
      ["✂️","scissors","scissors"],
      ["🗃️","card file box","card_file_box"],
      ["🗄️","file cabinet","file_cabinet"],
      ["🗑️","wastebasket","wastebasket"],
      ["🔒","locked","lock"],
      ["🔓","unlocked","unlock"],
      ["🔏","locked with pen","lock_with_ink_pen"],
      ["🔐","locked with key","closed_lock_with_key"],
      ["🔑","key","key"],
      ["🗝️","old key","old_key"],
      ["🔨","hammer","hammer"],
      ["🪓","axe","axe"],
      ["⛏️","pick","pick"],
      ["⚒️","hammer and pick","hammer_and_pick"],
      ["🛠️","hammer and wrench","hammer_and_wrench"],
      ["🗡️","dagger","dagger"],
      ["⚔️","crossed swords","crossed_swords"],
      ["💣","bomb","bomb"],
      ["🪃","boomerang","boomerang"],
      ["🏹","bow and arrow","bow_and_arrow"],
      ["🛡️","shield","shield"],
      ["🪚","carpentry saw","carpentry_saw"],
      ["🔧","wrench","wrench"],
      ["🪛","screwdriver","screwdriver"],
      ["🔩","nut and bolt","nut_and_bolt"],
      ["⚙️","gear","gear"],
      ["🗜️","clamp","clamp"],
      ["⚖️","balance scale","balance_scale"],
      ["🦯","white cane","probing_cane"],
      ["🔗","link","link"],
      ["⛓️","chains","chains"],
      ["🪝","hook","hook"],
      ["🧰","toolbox","toolbox"],
      ["🧲","magnet","magnet"],
      ["🪜","ladder","ladder"],
      ["⚗️","alembic","alembic"],
      ["🧪","test tube","test_tube"],
      ["🧫","petri dish","petri_dish"],
      ["🧬","dna","dna"],
      ["🔬","microscope","microscope"],
      ["🔭","telescope","telescope"],
      ["📡","satellite antenna","satellite"],
      ["💉","syringe","syringe"],
      ["🩸","drop of blood","drop_of_blood"],
      ["💊","pill","pill"],
      ["🩹","adhesive bandage","adhesive_bandage"],
      ["🩼","crutch","crutch"],
      ["🩺","stethoscope","stethoscope"],
      ["🩻","x-ray","x_ray"],
      ["🚪","door","door"],
      ["🛗","elevator","elevator"],
      ["🪞","mirror","mirror"],
      ["🪟","window","window"],
      ["🛏️","bed","bed"],
      ["🛋️","couch and lamp","couch_and_lamp"],
      ["🪑","chair","chair"],
      ["🚽","toilet","toilet"],
      ["🪠","plunger","plunger"],
      ["🚿","shower","shower"],
      ["🛁","bathtub","bathtub"],
      ["🪤","mouse trap","mouse_trap"],
      ["🪒","razor","razor"],
      ["🧴","lotion bottle","lotion_bottle"],
      ["🧷","safety pin","safety_pin"],
      ["🧹","broom","broom"],
      ["🧺","basket","basket"],
      ["🧻","roll of paper","roll_of_paper"],
      ["🪣","bucket","bucket"],
      ["🧼","soap","soap"],
      ["🫧","bubbles","bubbles"],
      ["🪥","toothbrush","toothbrush"],
      ["🧽","sponge","sponge"],
      ["🧯","fire extinguisher","fire_extinguisher"],
      ["🛒","shopping cart","shopping_cart"],
      ["🚬","cigarette","smoking"],
      ["⚰️","coffin","coffin"],
      ["🪦","headstone","headstone"],
      ["⚱️","funeral urn","funeral_urn"],
      ["🧿","nazar amulet","nazar_amulet"],
      ["🪬","hamsa","hamsa"],
      ["🗿","moai","moyai"],
      ["🪧","placard","placard"],
      ["🪪","identification card","identification_card"],
    ],
  },
  {
    name: "Symbols",
    items: [
      ["🏧","ATM sign","atm"],
      ["🚮","litter in bin sign","put_litter_in_its_place"],
      ["🚰","potable water","potable_water"],
      ["♿","wheelchair symbol","wheelchair"],
      ["🚹","men’s room","mens"],
      ["🚺","women’s room","womens"],
      ["🚻","restroom","restroom"],
      ["🚼","baby symbol","baby_symbol"],
      ["🚾","water closet","wc"],
      ["🛂","passport control","passport_control"],
      ["🛃","customs","customs"],
      ["🛄","baggage claim","baggage_claim"],
      ["🛅","left luggage","left_luggage"],
      ["⚠️","warning","warning"],
      ["🚸","children crossing","children_crossing"],
      ["⛔","no entry","no_entry"],
      ["🚫","prohibited","no_entry_sign"],
      ["🚳","no bicycles","no_bicycles"],
      ["🚭","no smoking","no_smoking"],
      ["🚯","no littering","do_not_litter"],
      ["🚱","non-potable water","non-potable_water"],
      ["🚷","no pedestrians","no_pedestrians"],
      ["📵","no mobile phones","no_mobile_phones"],
      ["🔞","no one under eighteen","underage"],
      ["☢️","radioactive","radioactive"],
      ["☣️","biohazard","biohazard"],
      ["⬆️","up arrow","arrow_up"],
      ["↗️","up-right arrow","arrow_upper_right"],
      ["➡️","right arrow","arrow_right"],
      ["↘️","down-right arrow","arrow_lower_right"],
      ["⬇️","down arrow","arrow_down"],
      ["↙️","down-left arrow","arrow_lower_left"],
      ["⬅️","left arrow","arrow_left"],
      ["↖️","up-left arrow","arrow_upper_left"],
      ["↕️","up-down arrow","arrow_up_down"],
      ["↔️","left-right arrow","left_right_arrow"],
      ["↩️","right arrow curving left","leftwards_arrow_with_hook"],
      ["↪️","left arrow curving right","arrow_right_hook"],
      ["⤴️","right arrow curving up","arrow_heading_up"],
      ["⤵️","right arrow curving down","arrow_heading_down"],
      ["🔃","clockwise vertical arrows","arrows_clockwise"],
      ["🔄","counterclockwise arrows button","arrows_counterclockwise"],
      ["🔙","BACK arrow","back"],
      ["🔚","END arrow","end"],
      ["🔛","ON! arrow","on"],
      ["🔜","SOON arrow","soon"],
      ["🔝","TOP arrow","top"],
      ["🛐","place of worship","place_of_worship"],
      ["⚛️","atom symbol","atom_symbol"],
      ["🕉️","om","om"],
      ["✡️","star of David","star_of_david"],
      ["☸️","wheel of dharma","wheel_of_dharma"],
      ["☯️","yin yang","yin_yang"],
      ["✝️","latin cross","latin_cross"],
      ["☦️","orthodox cross","orthodox_cross"],
      ["☪️","star and crescent","star_and_crescent"],
      ["☮️","peace symbol","peace_symbol"],
      ["🕎","menorah","menorah"],
      ["🔯","dotted six-pointed star","six_pointed_star"],
      ["🪯","khanda","khanda"],
      ["♈","Aries","aries"],
      ["♉","Taurus","taurus"],
      ["♊","Gemini","gemini"],
      ["♋","Cancer","cancer"],
      ["♌","Leo","leo"],
      ["♍","Virgo","virgo"],
      ["♎","Libra","libra"],
      ["♏","Scorpio","scorpius"],
      ["♐","Sagittarius","sagittarius"],
      ["♑","Capricorn","capricorn"],
      ["♒","Aquarius","aquarius"],
      ["♓","Pisces","pisces"],
      ["⛎","Ophiuchus","ophiuchus"],
      ["🔀","shuffle tracks button","twisted_rightwards_arrows"],
      ["🔁","repeat button","repeat"],
      ["🔂","repeat single button","repeat_one"],
      ["▶️","play button","arrow_forward"],
      ["⏩","fast-forward button","fast_forward"],
      ["⏭️","next track button","next_track_button"],
      ["⏯️","play or pause button","play_or_pause_button"],
      ["◀️","reverse button","arrow_backward"],
      ["⏪","fast reverse button","rewind"],
      ["⏮️","last track button","previous_track_button"],
      ["🔼","upwards button","arrow_up_small"],
      ["⏫","fast up button","arrow_double_up"],
      ["🔽","downwards button","arrow_down_small"],
      ["⏬","fast down button","arrow_double_down"],
      ["⏸️","pause button","pause_button"],
      ["⏹️","stop button","stop_button"],
      ["⏺️","record button","record_button"],
      ["⏏️","eject button","eject_button"],
      ["🎦","cinema","cinema"],
      ["🔅","dim button","low_brightness"],
      ["🔆","bright button","high_brightness"],
      ["📶","antenna bars","signal_strength"],
      ["🛜","wireless","wireless"],
      ["📳","vibration mode","vibration_mode"],
      ["📴","mobile phone off","mobile_phone_off"],
      ["♀️","female sign","female_sign"],
      ["♂️","male sign","male_sign"],
      ["⚧️","transgender symbol","transgender_symbol"],
      ["✖️","multiply","heavy_multiplication_x"],
      ["➕","plus","heavy_plus_sign"],
      ["➖","minus","heavy_minus_sign"],
      ["➗","divide","heavy_division_sign"],
      ["🟰","heavy equals sign","heavy_equals_sign"],
      ["♾️","infinity","infinity"],
      ["‼️","double exclamation mark","bangbang"],
      ["⁉️","exclamation question mark","interrobang"],
      ["❓","red question mark","question"],
      ["❔","white question mark","grey_question"],
      ["❕","white exclamation mark","grey_exclamation"],
      ["❗","red exclamation mark","exclamation|heavy_exclamation_mark"],
      ["〰️","wavy dash","wavy_dash"],
      ["💱","currency exchange","currency_exchange"],
      ["💲","heavy dollar sign","heavy_dollar_sign"],
      ["⚕️","medical symbol","medical_symbol"],
      ["♻️","recycling symbol","recycle"],
      ["⚜️","fleur-de-lis","fleur_de_lis"],
      ["🔱","trident emblem","trident"],
      ["📛","name badge","name_badge"],
      ["🔰","Japanese symbol for beginner","beginner"],
      ["⭕","hollow red circle","o"],
      ["✅","check mark button","white_check_mark"],
      ["☑️","check box with check","ballot_box_with_check"],
      ["✔️","check mark","heavy_check_mark"],
      ["❌","cross mark","x"],
      ["❎","cross mark button","negative_squared_cross_mark"],
      ["➰","curly loop","curly_loop"],
      ["➿","double curly loop","loop"],
      ["〽️","part alternation mark","part_alternation_mark"],
      ["✳️","eight-spoked asterisk","eight_spoked_asterisk"],
      ["✴️","eight-pointed star","eight_pointed_black_star"],
      ["❇️","sparkle","sparkle"],
      ["©️","copyright","copyright"],
      ["®️","registered","registered"],
      ["™️","trade mark","tm"],
      ["#️⃣","keycap: #","hash"],
      ["*️⃣","keycap: *","asterisk"],
      ["0️⃣","keycap: 0","zero"],
      ["1️⃣","keycap: 1","one"],
      ["2️⃣","keycap: 2","two"],
      ["3️⃣","keycap: 3","three"],
      ["4️⃣","keycap: 4","four"],
      ["5️⃣","keycap: 5","five"],
      ["6️⃣","keycap: 6","six"],
      ["7️⃣","keycap: 7","seven"],
      ["8️⃣","keycap: 8","eight"],
      ["9️⃣","keycap: 9","nine"],
      ["🔟","keycap: 10","keycap_ten"],
      ["🔠","input latin uppercase","capital_abcd"],
      ["🔡","input latin lowercase","abcd"],
      ["🔢","input numbers","1234"],
      ["🔣","input symbols","symbols"],
      ["🔤","input latin letters","abc"],
      ["🅰️","A button (blood type)","a"],
      ["🆎","AB button (blood type)","ab"],
      ["🅱️","B button (blood type)","b"],
      ["🆑","CL button","cl"],
      ["🆒","COOL button","cool"],
      ["🆓","FREE button","free"],
      ["ℹ️","information","information_source"],
      ["🆔","ID button","id"],
      ["Ⓜ️","circled M","m"],
      ["🆕","NEW button","new"],
      ["🆖","NG button","ng"],
      ["🅾️","O button (blood type)","o2"],
      ["🆗","OK button","ok"],
      ["🅿️","P button","parking"],
      ["🆘","SOS button","sos"],
      ["🆙","UP! button","up"],
      ["🆚","VS button","vs"],
      ["🈁","Japanese “here” button","koko"],
      ["🈂️","Japanese “service charge” button","sa"],
      ["🈷️","Japanese “monthly amount” button","u6708"],
      ["🈶","Japanese “not free of charge” button","u6709"],
      ["🈯","Japanese “reserved” button","u6307"],
      ["🉐","Japanese “bargain” button","ideograph_advantage"],
      ["🈹","Japanese “discount” button","u5272"],
      ["🈚","Japanese “free of charge” button","u7121"],
      ["🈲","Japanese “prohibited” button","u7981"],
      ["🉑","Japanese “acceptable” button","accept"],
      ["🈸","Japanese “application” button","u7533"],
      ["🈴","Japanese “passing grade” button","u5408"],
      ["🈳","Japanese “vacancy” button","u7a7a"],
      ["㊗️","Japanese “congratulations” button","congratulations"],
      ["㊙️","Japanese “secret” button","secret"],
      ["🈺","Japanese “open for business” button","u55b6"],
      ["🈵","Japanese “no vacancy” button","u6e80"],
      ["🔴","red circle","red_circle"],
      ["🟠","orange circle","orange_circle"],
      ["🟡","yellow circle","yellow_circle"],
      ["🟢","green circle","green_circle"],
      ["🔵","blue circle","large_blue_circle"],
      ["🟣","purple circle","purple_circle"],
      ["🟤","brown circle","brown_circle"],
      ["⚫","black circle","black_circle"],
      ["⚪","white circle","white_circle"],
      ["🟥","red square","red_square"],
      ["🟧","orange square","orange_square"],
      ["🟨","yellow square","yellow_square"],
      ["🟩","green square","green_square"],
      ["🟦","blue square","blue_square"],
      ["🟪","purple square","purple_square"],
      ["🟫","brown square","brown_square"],
      ["⬛","black large square","black_large_square"],
      ["⬜","white large square","white_large_square"],
      ["◼️","black medium square","black_medium_square"],
      ["◻️","white medium square","white_medium_square"],
      ["◾","black medium-small square","black_medium_small_square"],
      ["◽","white medium-small square","white_medium_small_square"],
      ["▪️","black small square","black_small_square"],
      ["▫️","white small square","white_small_square"],
      ["🔶","large orange diamond","large_orange_diamond"],
      ["🔷","large blue diamond","large_blue_diamond"],
      ["🔸","small orange diamond","small_orange_diamond"],
      ["🔹","small blue diamond","small_blue_diamond"],
      ["🔺","red triangle pointed up","small_red_triangle"],
      ["🔻","red triangle pointed down","small_red_triangle_down"],
      ["💠","diamond with a dot","diamond_shape_with_a_dot_inside"],
      ["🔘","radio button","radio_button"],
      ["🔳","white square button","white_square_button"],
      ["🔲","black square button","black_square_button"],
    ],
  },
  {
    name: "Flags",
    items: [
      ["🏁","chequered flag","checkered_flag"],
      ["🚩","triangular flag","triangular_flag_on_post"],
      ["🎌","crossed flags","crossed_flags"],
      ["🏴","black flag","black_flag"],
      ["🏳️","white flag","white_flag"],
      ["🏳️‍🌈","rainbow flag","rainbow_flag"],
      ["🏳️‍⚧️","transgender flag","transgender_flag"],
      ["🏴‍☠️","pirate flag","pirate_flag"],
      ["🇦🇨","flag: Ascension Island","ascension_island"],
      ["🇦🇩","flag: Andorra","andorra"],
      ["🇦🇪","flag: United Arab Emirates","united_arab_emirates"],
      ["🇦🇫","flag: Afghanistan","afghanistan"],
      ["🇦🇬","flag: Antigua & Barbuda","antigua_barbuda"],
      ["🇦🇮","flag: Anguilla","anguilla"],
      ["🇦🇱","flag: Albania","albania"],
      ["🇦🇲","flag: Armenia","armenia"],
      ["🇦🇴","flag: Angola","angola"],
      ["🇦🇶","flag: Antarctica","antarctica"],
      ["🇦🇷","flag: Argentina","argentina"],
      ["🇦🇸","flag: American Samoa","american_samoa"],
      ["🇦🇹","flag: Austria","austria"],
      ["🇦🇺","flag: Australia","australia"],
      ["🇦🇼","flag: Aruba","aruba"],
      ["🇦🇽","flag: Åland Islands","aland_islands"],
      ["🇦🇿","flag: Azerbaijan","azerbaijan"],
      ["🇧🇦","flag: Bosnia & Herzegovina","bosnia_herzegovina"],
      ["🇧🇧","flag: Barbados","barbados"],
      ["🇧🇩","flag: Bangladesh","bangladesh"],
      ["🇧🇪","flag: Belgium","belgium"],
      ["🇧🇫","flag: Burkina Faso","burkina_faso"],
      ["🇧🇬","flag: Bulgaria","bulgaria"],
      ["🇧🇭","flag: Bahrain","bahrain"],
      ["🇧🇮","flag: Burundi","burundi"],
      ["🇧🇯","flag: Benin","benin"],
      ["🇧🇱","flag: St. Barthélemy","st_barthelemy"],
      ["🇧🇲","flag: Bermuda","bermuda"],
      ["🇧🇳","flag: Brunei","brunei"],
      ["🇧🇴","flag: Bolivia","bolivia"],
      ["🇧🇶","flag: Caribbean Netherlands","caribbean_netherlands"],
      ["🇧🇷","flag: Brazil","brazil"],
      ["🇧🇸","flag: Bahamas","bahamas"],
      ["🇧🇹","flag: Bhutan","bhutan"],
      ["🇧🇻","flag: Bouvet Island","bouvet_island"],
      ["🇧🇼","flag: Botswana","botswana"],
      ["🇧🇾","flag: Belarus","belarus"],
      ["🇧🇿","flag: Belize","belize"],
      ["🇨🇦","flag: Canada","canada"],
      ["🇨🇨","flag: Cocos (Keeling) Islands","cocos_islands"],
      ["🇨🇩","flag: Congo - Kinshasa","congo_kinshasa"],
      ["🇨🇫","flag: Central African Republic","central_african_republic"],
      ["🇨🇬","flag: Congo - Brazzaville","congo_brazzaville"],
      ["🇨🇭","flag: Switzerland","switzerland"],
      ["🇨🇮","flag: Côte d’Ivoire","cote_divoire"],
      ["🇨🇰","flag: Cook Islands","cook_islands"],
      ["🇨🇱","flag: Chile","chile"],
      ["🇨🇲","flag: Cameroon","cameroon"],
      ["🇨🇳","flag: China","cn"],
      ["🇨🇴","flag: Colombia","colombia"],
      ["🇨🇵","flag: Clipperton Island","clipperton_island"],
      ["🇨🇷","flag: Costa Rica","costa_rica"],
      ["🇨🇺","flag: Cuba","cuba"],
      ["🇨🇻","flag: Cape Verde","cape_verde"],
      ["🇨🇼","flag: Curaçao","curacao"],
      ["🇨🇽","flag: Christmas Island","christmas_island"],
      ["🇨🇾","flag: Cyprus","cyprus"],
      ["🇨🇿","flag: Czechia","czech_republic"],
      ["🇩🇪","flag: Germany","de"],
      ["🇩🇬","flag: Diego Garcia","diego_garcia"],
      ["🇩🇯","flag: Djibouti","djibouti"],
      ["🇩🇰","flag: Denmark","denmark"],
      ["🇩🇲","flag: Dominica","dominica"],
      ["🇩🇴","flag: Dominican Republic","dominican_republic"],
      ["🇩🇿","flag: Algeria","algeria"],
      ["🇪🇦","flag: Ceuta & Melilla","ceuta_melilla"],
      ["🇪🇨","flag: Ecuador","ecuador"],
      ["🇪🇪","flag: Estonia","estonia"],
      ["🇪🇬","flag: Egypt","egypt"],
      ["🇪🇭","flag: Western Sahara","western_sahara"],
      ["🇪🇷","flag: Eritrea","eritrea"],
      ["🇪🇸","flag: Spain","es"],
      ["🇪🇹","flag: Ethiopia","ethiopia"],
      ["🇪🇺","flag: European Union","eu|european_union"],
      ["🇫🇮","flag: Finland","finland"],
      ["🇫🇯","flag: Fiji","fiji"],
      ["🇫🇰","flag: Falkland Islands","falkland_islands"],
      ["🇫🇲","flag: Micronesia","micronesia"],
      ["🇫🇴","flag: Faroe Islands","faroe_islands"],
      ["🇫🇷","flag: France","fr"],
      ["🇬🇦","flag: Gabon","gabon"],
      ["🇬🇧","flag: United Kingdom","gb|uk"],
      ["🇬🇩","flag: Grenada","grenada"],
      ["🇬🇪","flag: Georgia","georgia"],
      ["🇬🇫","flag: French Guiana","french_guiana"],
      ["🇬🇬","flag: Guernsey","guernsey"],
      ["🇬🇭","flag: Ghana","ghana"],
      ["🇬🇮","flag: Gibraltar","gibraltar"],
      ["🇬🇱","flag: Greenland","greenland"],
      ["🇬🇲","flag: Gambia","gambia"],
      ["🇬🇳","flag: Guinea","guinea"],
      ["🇬🇵","flag: Guadeloupe","guadeloupe"],
      ["🇬🇶","flag: Equatorial Guinea","equatorial_guinea"],
      ["🇬🇷","flag: Greece","greece"],
      ["🇬🇸","flag: South Georgia & South Sandwich Islands","south_georgia_south_sandwich_islands"],
      ["🇬🇹","flag: Guatemala","guatemala"],
      ["🇬🇺","flag: Guam","guam"],
      ["🇬🇼","flag: Guinea-Bissau","guinea_bissau"],
      ["🇬🇾","flag: Guyana","guyana"],
      ["🇭🇰","flag: Hong Kong SAR China","hong_kong"],
      ["🇭🇲","flag: Heard & McDonald Islands","heard_mcdonald_islands"],
      ["🇭🇳","flag: Honduras","honduras"],
      ["🇭🇷","flag: Croatia","croatia"],
      ["🇭🇹","flag: Haiti","haiti"],
      ["🇭🇺","flag: Hungary","hungary"],
      ["🇮🇨","flag: Canary Islands","canary_islands"],
      ["🇮🇩","flag: Indonesia","indonesia"],
      ["🇮🇪","flag: Ireland","ireland"],
      ["🇮🇱","flag: Israel","israel"],
      ["🇮🇲","flag: Isle of Man","isle_of_man"],
      ["🇮🇳","flag: India","india"],
      ["🇮🇴","flag: British Indian Ocean Territory","british_indian_ocean_territory"],
      ["🇮🇶","flag: Iraq","iraq"],
      ["🇮🇷","flag: Iran","iran"],
      ["🇮🇸","flag: Iceland","iceland"],
      ["🇮🇹","flag: Italy","it"],
      ["🇯🇪","flag: Jersey","jersey"],
      ["🇯🇲","flag: Jamaica","jamaica"],
      ["🇯🇴","flag: Jordan","jordan"],
      ["🇯🇵","flag: Japan","jp"],
      ["🇰🇪","flag: Kenya","kenya"],
      ["🇰🇬","flag: Kyrgyzstan","kyrgyzstan"],
      ["🇰🇭","flag: Cambodia","cambodia"],
      ["🇰🇮","flag: Kiribati","kiribati"],
      ["🇰🇲","flag: Comoros","comoros"],
      ["🇰🇳","flag: St. Kitts & Nevis","st_kitts_nevis"],
      ["🇰🇵","flag: North Korea","north_korea"],
      ["🇰🇷","flag: South Korea","kr"],
      ["🇰🇼","flag: Kuwait","kuwait"],
      ["🇰🇾","flag: Cayman Islands","cayman_islands"],
      ["🇰🇿","flag: Kazakhstan","kazakhstan"],
      ["🇱🇦","flag: Laos","laos"],
      ["🇱🇧","flag: Lebanon","lebanon"],
      ["🇱🇨","flag: St. Lucia","st_lucia"],
      ["🇱🇮","flag: Liechtenstein","liechtenstein"],
      ["🇱🇰","flag: Sri Lanka","sri_lanka"],
      ["🇱🇷","flag: Liberia","liberia"],
      ["🇱🇸","flag: Lesotho","lesotho"],
      ["🇱🇹","flag: Lithuania","lithuania"],
      ["🇱🇺","flag: Luxembourg","luxembourg"],
      ["🇱🇻","flag: Latvia","latvia"],
      ["🇱🇾","flag: Libya","libya"],
      ["🇲🇦","flag: Morocco","morocco"],
      ["🇲🇨","flag: Monaco","monaco"],
      ["🇲🇩","flag: Moldova","moldova"],
      ["🇲🇪","flag: Montenegro","montenegro"],
      ["🇲🇫","flag: St. Martin","st_martin"],
      ["🇲🇬","flag: Madagascar","madagascar"],
      ["🇲🇭","flag: Marshall Islands","marshall_islands"],
      ["🇲🇰","flag: North Macedonia","macedonia"],
      ["🇲🇱","flag: Mali","mali"],
      ["🇲🇲","flag: Myanmar (Burma)","myanmar"],
      ["🇲🇳","flag: Mongolia","mongolia"],
      ["🇲🇴","flag: Macao SAR China","macau"],
      ["🇲🇵","flag: Northern Mariana Islands","northern_mariana_islands"],
      ["🇲🇶","flag: Martinique","martinique"],
      ["🇲🇷","flag: Mauritania","mauritania"],
      ["🇲🇸","flag: Montserrat","montserrat"],
      ["🇲🇹","flag: Malta","malta"],
      ["🇲🇺","flag: Mauritius","mauritius"],
      ["🇲🇻","flag: Maldives","maldives"],
      ["🇲🇼","flag: Malawi","malawi"],
      ["🇲🇽","flag: Mexico","mexico"],
      ["🇲🇾","flag: Malaysia","malaysia"],
      ["🇲🇿","flag: Mozambique","mozambique"],
      ["🇳🇦","flag: Namibia","namibia"],
      ["🇳🇨","flag: New Caledonia","new_caledonia"],
      ["🇳🇪","flag: Niger","niger"],
      ["🇳🇫","flag: Norfolk Island","norfolk_island"],
      ["🇳🇬","flag: Nigeria","nigeria"],
      ["🇳🇮","flag: Nicaragua","nicaragua"],
      ["🇳🇱","flag: Netherlands","netherlands"],
      ["🇳🇴","flag: Norway","norway"],
      ["🇳🇵","flag: Nepal","nepal"],
      ["🇳🇷","flag: Nauru","nauru"],
      ["🇳🇺","flag: Niue","niue"],
      ["🇳🇿","flag: New Zealand","new_zealand"],
      ["🇴🇲","flag: Oman","oman"],
      ["🇵🇦","flag: Panama","panama"],
      ["🇵🇪","flag: Peru","peru"],
      ["🇵🇫","flag: French Polynesia","french_polynesia"],
      ["🇵🇬","flag: Papua New Guinea","papua_new_guinea"],
      ["🇵🇭","flag: Philippines","philippines"],
      ["🇵🇰","flag: Pakistan","pakistan"],
      ["🇵🇱","flag: Poland","poland"],
      ["🇵🇲","flag: St. Pierre & Miquelon","st_pierre_miquelon"],
      ["🇵🇳","flag: Pitcairn Islands","pitcairn_islands"],
      ["🇵🇷","flag: Puerto Rico","puerto_rico"],
      ["🇵🇸","flag: Palestinian Territories","palestinian_territories"],
      ["🇵🇹","flag: Portugal","portugal"],
      ["🇵🇼","flag: Palau","palau"],
      ["🇵🇾","flag: Paraguay","paraguay"],
      ["🇶🇦","flag: Qatar","qatar"],
      ["🇷🇪","flag: Réunion","reunion"],
      ["🇷🇴","flag: Romania","romania"],
      ["🇷🇸","flag: Serbia","serbia"],
      ["🇷🇺","flag: Russia","ru"],
      ["🇷🇼","flag: Rwanda","rwanda"],
      ["🇸🇦","flag: Saudi Arabia","saudi_arabia"],
      ["🇸🇧","flag: Solomon Islands","solomon_islands"],
      ["🇸🇨","flag: Seychelles","seychelles"],
      ["🇸🇩","flag: Sudan","sudan"],
      ["🇸🇪","flag: Sweden","sweden"],
      ["🇸🇬","flag: Singapore","singapore"],
      ["🇸🇭","flag: St. Helena","st_helena"],
      ["🇸🇮","flag: Slovenia","slovenia"],
      ["🇸🇯","flag: Svalbard & Jan Mayen","svalbard_jan_mayen"],
      ["🇸🇰","flag: Slovakia","slovakia"],
      ["🇸🇱","flag: Sierra Leone","sierra_leone"],
      ["🇸🇲","flag: San Marino","san_marino"],
      ["🇸🇳","flag: Senegal","senegal"],
      ["🇸🇴","flag: Somalia","somalia"],
      ["🇸🇷","flag: Suriname","suriname"],
      ["🇸🇸","flag: South Sudan","south_sudan"],
      ["🇸🇹","flag: São Tomé & Príncipe","sao_tome_principe"],
      ["🇸🇻","flag: El Salvador","el_salvador"],
      ["🇸🇽","flag: Sint Maarten","sint_maarten"],
      ["🇸🇾","flag: Syria","syria"],
      ["🇸🇿","flag: Eswatini","swaziland"],
      ["🇹🇦","flag: Tristan da Cunha","tristan_da_cunha"],
      ["🇹🇨","flag: Turks & Caicos Islands","turks_caicos_islands"],
      ["🇹🇩","flag: Chad","chad"],
      ["🇹🇫","flag: French Southern Territories","french_southern_territories"],
      ["🇹🇬","flag: Togo","togo"],
      ["🇹🇭","flag: Thailand","thailand"],
      ["🇹🇯","flag: Tajikistan","tajikistan"],
      ["🇹🇰","flag: Tokelau","tokelau"],
      ["🇹🇱","flag: Timor-Leste","timor_leste"],
      ["🇹🇲","flag: Turkmenistan","turkmenistan"],
      ["🇹🇳","flag: Tunisia","tunisia"],
      ["🇹🇴","flag: Tonga","tonga"],
      ["🇹🇷","flag: Turkey","tr"],
      ["🇹🇹","flag: Trinidad & Tobago","trinidad_tobago"],
      ["🇹🇻","flag: Tuvalu","tuvalu"],
      ["🇹🇼","flag: Taiwan","taiwan"],
      ["🇹🇿","flag: Tanzania","tanzania"],
      ["🇺🇦","flag: Ukraine","ukraine"],
      ["🇺🇬","flag: Uganda","uganda"],
      ["🇺🇲","flag: U.S. Outlying Islands","us_outlying_islands"],
      ["🇺🇳","flag: United Nations","united_nations"],
      ["🇺🇸","flag: United States","us"],
      ["🇺🇾","flag: Uruguay","uruguay"],
      ["🇺🇿","flag: Uzbekistan","uzbekistan"],
      ["🇻🇦","flag: Vatican City","vatican_city"],
      ["🇻🇨","flag: St. Vincent & Grenadines","st_vincent_grenadines"],
      ["🇻🇪","flag: Venezuela","venezuela"],
      ["🇻🇬","flag: British Virgin Islands","british_virgin_islands"],
      ["🇻🇮","flag: U.S. Virgin Islands","us_virgin_islands"],
      ["🇻🇳","flag: Vietnam","vietnam"],
      ["🇻🇺","flag: Vanuatu","vanuatu"],
      ["🇼🇫","flag: Wallis & Futuna","wallis_futuna"],
      ["🇼🇸","flag: Samoa","samoa"],
      ["🇽🇰","flag: Kosovo","kosovo"],
      ["🇾🇪","flag: Yemen","yemen"],
      ["🇾🇹","flag: Mayotte","mayotte"],
      ["🇿🇦","flag: South Africa","south_africa"],
      ["🇿🇲","flag: Zambia","zambia"],
      ["🇿🇼","flag: Zimbabwe","zimbabwe"],
      ["🏴󠁧󠁢󠁥󠁮󠁧󠁿","flag: England","england"],
      ["🏴󠁧󠁢󠁳󠁣󠁴󠁿","flag: Scotland","scotland"],
      ["🏴󠁧󠁢󠁷󠁬󠁳󠁿","flag: Wales","wales"],
    ],
  },
];
